
'use client';

import React, { createContext, useState, useContext, ReactNode } from 'react';

type Language = 'en' | 'hi' | 'es';

type LanguageContextType = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
};

const translations = {
  en: {
    site_title: 'GR7 Tools Hub',
    welcome: 'Welcome to GR7 Tools Hub',
    english: 'English',
    hindi: 'Hindi',
    spanish: 'Spanish',
    language: 'Language',
    home: 'Home',
    tagline: 'Fast, private, and professional browser tools.',
    image_tools: 'IMAGE TOOLS',
    pdf_tools: 'PDF TOOLS',
    file_tools: 'FILE TOOLS',
    audio_tools: 'AUDIO TOOLS',
    video_tools: 'VIDEO TOOLS',
    calculator_pro: 'CALCULATORS',
    converter_tools: 'CONVERTERS',
    image_compress_label: 'IMAGE COMPRESS',
    image_compress_description: 'Reduce image file size without losing quality.',
    resize_image_label: 'IMAGE RESIZER',
    resize_image_description: 'Change image dimensions for official forms.',
    signature_resizer_label: 'SIGNATURE RESIZER',
    signature_resizer_description: 'Resize signature to exact CM/Pixel and KB size.',
    crop_image_label: 'CROP IMAGE',
    crop_image_description: 'Easily crop your images to the perfect size.',
    passport_photo_label: 'PASSPORT PHOTO MAKER',
    passport_photo_description: 'Create professional passport-sized photos instantly.',
    passport_date_name_label: 'ADD NAME & DATE TO PHOTO',
    passport_date_name_description: 'Add professional Name and Date of Photo (DOP) on passport size images.',
    aadhaar_printer_label: 'AADHAAR CARD PRINTER',
    aadhaar_printer_description: 'Auto-crop and arrange e-Aadhaar for easy printing.',
    image_to_jpg_label: 'IMAGE TO JPG',
    image_to_jpg_description: 'Convert various image formats to JPG.',
    image_to_png_label: 'IMAGE TO PNG',
    image_to_png_description: 'Convert various image formats to PNG.',
    image_to_pdf_label: 'IMAGE TO PDF',
    image_to_pdf_description: 'Convert images into a single PDF file.',
    html_to_pdf_label: 'HTML TO PDF',
    html_to_pdf_description: 'Convert raw HTML code into a PDF document.',
    pdf_to_image_label: 'PDF TO IMAGE',
    pdf_to_image_description: 'Extract all pages from a PDF as images.',
    compress_pdf_label: 'PDF COMPRESS',
    compress_pdf_description: 'Reduce the file size of your PDF documents.',
    merge_pdf_label: 'MERGE PDF',
    merge_pdf_description: 'Combine multiple PDFs into one document.',
    split_pdf_label: 'SPLIT PDF',
    split_pdf_description: 'Extract specific pages from a PDF.',
    rotate_pdf_label: 'ROTATE PDF',
    rotate_pdf_description: 'Rotate PDF pages permanently and save.',
    organize_pdf_label: 'ORGANIZE PDF',
    organize_pdf_description: 'Delete, reorder and rotate pages visually.',
    crop_pdf_label: 'CROP PDF',
    crop_pdf_description: 'Crop the visible area of PDF pages.',
    edit_pdf_label: 'EDIT PDF',
    edit_pdf_description: 'Add text, images, and reorganize pages in your PDF.',
    document_scan_label: 'DOCUMENT SCAN',
    document_scan_description: 'Premium scanner with BW PRO and Magic Color filters.',
    unlock_pdf_label: 'UNLOCK PDF',
    unlock_pdf_description: 'Remove password protection from a PDF.',
    lock_pdf_label: 'PDF LOCKER',
    lock_pdf_description: 'Protect your PDF with secure AES encryption.',
    add_watermark_label: 'ADD WATERMARK',
    add_watermark_description: 'Add a text watermark to your PDF.',
    add_page_numbers_label: 'ADD PAGE NUMBERS',
    add_page_numbers_description: 'Insert professional page numbers into PDFs.',
    audio_converter_label: 'AUDIO CONVERTER',
    audio_converter_description: 'Convert between MP3, WAV, OGG and M4A instantly.',
    audio_merger_label: 'AUDIO MERGER',
    audio_merger_description: 'Combine multiple audio tracks into a single file.',
    video_to_mp3_label: 'VIDEO TO MP3',
    video_to_mp3_description: 'Extract high-quality audio from video files instantly.',
    mp3_cutter_label: 'MP3 CUTTER & AUDIO STUDIO',
    mp3_cutter_description: 'Trim, cut and enhance audio files with precise waveform control.',
    create_zip_label: 'CREATE ZIP',
    create_zip_description: 'Combine multiple files into a single zip.',
    unzip_file_label: 'UNZIP FILE',
    unzip_file_description: 'Extract files from a zip archive.',
    standard_calculator_label: 'STANDARD CALCULATOR',
    standard_calculator_description: 'For your everyday calculations.',
    loan_emi_calculator_label: 'LOAN & EMI CALCULATOR',
    loan_emi_calculator_description: 'Calculate your loan payments ease.',
    mortgage_calculator_label: 'MORTGAGE CALCULATOR',
    mortgage_calculator_description: 'Comprehensive home loan & interest estimator.',
    age_calculator_label: 'AGE CALCULATOR',
    age_calculator_description: 'Find out your exact age profile.',
    percentage_calculator_label: 'PERCENTAGE CALCULATOR',
    percentage_calculator_description: 'Quickly calculate percentages.',
    gst_calculator_label: 'GST CALCULATOR',
    gst_calculator_description: 'Calculate GST Addition or Removal instantly.',
    gst_invoice_label: 'GST INVOICE GENERATOR',
    gst_invoice_description: 'Generate professional GST invoices instantly.',
    salary_slip_label: 'SALARY SLIP GENERATOR',
    salary_slip_description: 'Create professional A4 pay slips for employees instantly.',
    sip_calculator_label: 'SIP CALCULATOR',
    sip_calculator_description: 'Calculate returns on your monthly mutual fund investments.',
    fd_rd_calculator_label: 'FD & RD CALCULATOR',
    fd_rd_calculator_description: 'Calculate returns on Fixed and Recurring Deposits.',
    income_tax_calculator_label: 'INCOME TAX CALCULATOR',
    income_tax_calculator_description: 'Calculate tax based on new Indian regime.',
    acceleration_converter_label: 'ACCELERATION CONVERTER',
    acceleration_converter_description: 'Convert between different units.',
    area_converter_label: 'AREA CONVERTER',
    area_converter_description: 'Convert between different area units.',
    fuel_converter_label: 'FUEL CONVERTER',
    fuel_converter_description: 'Convert between efficiency units.',
    pressure_converter_label: 'PRESSURE CONVERTER',
    pressure_converter_description: 'Convert between different units.',
    fuel_cost_calculator_label: 'FUEL COST CALCULATOR',
    fuel_cost_calculator_description: 'Estimate trip fuel expenses.',
    interest_calculator_label: 'INTEREST CALCULATOR',
    interest_calculator_description: 'Simple and compound interest.',
    sales_tax_calculator_label: 'SALES TAX CALCULATOR',
    sales_tax_calculator_description: 'Calculate tax and total price.',
    color_picker_label: 'COLOR PICKER STUDIO',
    color_picker_description: 'Professional color palette generator with contrast checker.',
    search_tools_placeholder: 'Search for tools...',
    no_tools_found: 'No tools found',
    remove_background_label: 'BACKGROUND REMOVER',
    remove_background_description: 'Automatically remove background from any image.',
    remove_signature_label: 'SIGNATURE BG REMOVER',
    remove_signature_description: 'Extract clean signatures from paper photos.',
    enhance_photo_label: 'PHOTO ENHANCER',
    enhance_photo_description: 'Improve photo quality professionally.',
    image_to_text_label: 'IMAGE TO TEXT (OCR)',
    image_to_text_description: 'Extract text from any image locally.',
    text_to_pdf_label: 'TEXT TO PDF',
    text_to_pdf_description: 'Convert plain text into a PDF document.',
    barcode_generator_label: 'BARCODE GENERATOR',
    barcode_generator_description: 'Create scannable barcodes in various formats instantly.',
    qr_code_generator_label: 'QR CODE GENERATOR',
    qr_code_generator_description: 'Generate custom QR codes with logos and gradients instantly.',
    ai_upscaler_label: 'AI UPSCALER',
    ai_upscaler_description: 'Upscale images to 2x and 4x using browser AI.',
    privacy_policy: 'Privacy Policy',
    terms_of_service: 'Terms of Service',
  },
  hi: {
    site_title: 'GR7 टूल्स हब',
    welcome: 'GR7 टूल्स हब में आपका स्वागत है',
    english: 'अंग्रेज़ी',
    hindi: 'हिंदी',
    spanish: 'स्पेनिश',
    language: 'भाषा',
    home: 'होम',
    tagline: 'तेज़, निजी और पेशेवर ब्राउज़र उपकरण।',
    image_tools: 'इमेज टूल्स',
    pdf_tools: 'पीडीएफ टूल्स',
    file_tools: 'फ़ाइल टूल्स',
    audio_tools: 'ऑडियो टूल्स',
    video_tools: 'वीडियो टूल्स',
    calculator_pro: 'कैलकुलेटर प्रो',
    converter_tools: 'कन्वर्टर्स',
    image_compress_label: 'IMAGE COMPRESS',
    image_compress_description: 'गुणवत्ता खोए बिना आकार कम करें।',
    resize_image_label: 'IMAGE RESIZER',
    resize_image_description: 'छवि के आयाम तुरंत बदलें।',
    signature_resizer_label: 'SIGNATURE RESIZER',
    signature_resizer_description: 'सिग्नेचर को सही CM/Pixel aur KB साइज में बदलें।',
    crop_image_label: 'CROP IMAGE',
    crop_image_description: 'छवियों को सही आकार में काटें।',
    passport_photo_label: 'PASSPORT PHOTO MAKER',
    passport_photo_description: 'प्रोफेशनल पासपोर्ट फोटो तुरंत बनाएं।',
    passport_date_name_label: 'ADD NAME & DATE TO PHOTO',
    passport_date_name_description: 'पासपोर्ट फोटो पर पेशेवर रूप से नाम और तारीख जोड़ें।',
    aadhaar_printer_label: 'AADHAAR CARD PRINTER',
    aadhaar_printer_description: 'ई-आधार को व्यवस्थित और प्रिंट करें।',
    image_to_jpg_label: 'IMAGE TO JPG',
    image_to_jpg_description: 'छवियों को JPG में बदलें।',
    image_to_png_label: 'IMAGE TO PNG',
    image_to_png_description: 'छवियों को PNG में बदलें।',
    image_to_pdf_label: 'IMAGE TO PDF',
    image_to_pdf_description: 'छवियों को एक पीडीएफ फाइल में बदलें।',
    html_to_pdf_label: 'HTML TO PDF',
    html_to_pdf_description: 'HTML कोड को PDF में बदलें।',
    pdf_to_image_label: 'PDF TO IMAGE',
    pdf_to_image_description: 'PDF के पन्नों को इमेज में निकालें।',
    compress_pdf_label: 'PDF COMPRESS',
    compress_pdf_description: 'PDF फ़ाइल का आकार कम करें।',
    merge_pdf_label: 'MERGE PDF',
    merge_pdf_description: 'कई PDF को एक में मिलाएं।',
    split_pdf_label: 'SPLIT PDF',
    split_pdf_description: 'PDF से विशिष्ट पन्ने निकालें।',
    rotate_pdf_label: 'ROTATE PDF',
    rotate_pdf_description: 'PDF पन्नों को घुमाएं और सेव करें।',
    organize_pdf_label: 'ORGANIZE PDF',
    organize_pdf_description: 'पन्नों को डिलीट, व्यवस्थित और रोटेट करें।',
    crop_pdf_label: 'CROP PDF',
    crop_pdf_description: 'PDF पन्नों को क्रॉप करें।',
    edit_pdf_label: 'EDIT PDF',
    edit_pdf_description: 'PDF में टेक्स्ट, इमेज जोड़ें और पन्नों को व्यवस्थित करें।',
    document_scan_label: 'DOCUMENT SCAN',
    document_scan_description: 'BW PRO और मैजिक कलर फिल्टर के साथ प्रीमियम स्कैनर।',
    unlock_pdf_label: 'UNLOCK PDF',
    unlock_pdf_description: 'PDF से पासवर्ड हटाएं।',
    lock_pdf_label: 'PDF LOCKER',
    lock_pdf_description: 'PDF को पासवर्ड से सुरक्षित करें।',
    add_watermark_label: 'ADD WATERMARK',
    add_watermark_description: 'PDF में वॉटरमार्क टेक्स्ट जोड़ें।',
    add_page_numbers_label: 'ADD PAGE NUMBERS',
    add_page_numbers_description: 'PDF में पेज नंबर डालें।',
    audio_converter_label: 'ऑडियो कनवर्टर',
    audio_converter_description: 'MP3, WAV, OGG और M4A के बीच तुरंत कनवर्ट करें।',
    audio_merger_label: 'ऑडियो मर्जर',
    audio_merger_description: 'कई ऑडियो ट्रैक्स को एक साथ जोड़ें।',
    video_to_mp3_label: 'VIDEO TO MP3',
    video_to_mp3_description: 'वीडियो फ़ाइलों से तुरंत ऑडियो निकालें।',
    mp3_cutter_label: 'MP3 CUTTER & AUDIO STUDIO',
    mp3_cutter_description: 'सटीक वेवफॉर्म कंट्रोल के साथ ऑडियो फ़ाइलों को ट्रिम और एडिट करें।',
    create_zip_label: 'CREATE ZIP',
    create_zip_description: 'कई फ़ाइलों को ज़िप में मिलाएं।',
    unzip_file_label: 'UNZIP FILE',
    unzip_file_description: 'ज़िप से फ़ाइलें निकालें।',
    standard_calculator_label: 'STANDARD CALCULATOR',
    standard_calculator_description: 'रोजमर्रा की गणना के लिए।',
    loan_emi_calculator_label: 'LOAN & EMI CALCULATOR',
    loan_emi_calculator_description: 'ऋण भुगतान की गणना करें।',
    mortgage_calculator_label: 'MORTGAGE CALCULATOR',
    mortgage_calculator_description: 'व्यापक गृह ऋण और ब्याज अनुमानक।',
    age_calculator_label: 'AGE CALCULATOR',
    age_calculator_description: 'अपनी सटीक आयु प्रोफाइल देखें।',
    percentage_calculator_label: 'PERCENTAGE CALCULATOR',
    percentage_calculator_description: 'प्रतिशत की गणना करें।',
    gst_calculator_label: 'GST CALCULATOR',
    gst_calculator_description: 'जीएसटी जोड़ें या हटाएं तुरंत।',
    gst_invoice_label: 'GST INVOICE GENERATOR',
    gst_invoice_description: 'पेशेवर GST इनवॉइस तुरंत बनाएं।',
    salary_slip_label: 'SALARY SLIP GENERATOR',
    salary_slip_description: 'कर्मचारियों के लिए पेशेवर A4 सैलरी स्लिप तुरंत बनाएं।',
    sip_calculator_label: 'SIP CALCULATOR',
    sip_calculator_description: 'अपने म्यूचुअल फंड SIP रिटर्न की गणना करें।',
    fd_rd_calculator_label: 'FD & RD CALCULATOR',
    fd_rd_calculator_description: 'फिक्स्ड और रिकरिंग डिपॉजिट पर रिटर्न की गणना करें।',
    income_tax_calculator_label: 'INCOME TAX CALCULATOR',
    income_tax_calculator_description: 'नई भारतीय व्यवस्था के आधार पर टैक्स देखें।',
    acceleration_converter_label: 'ACCELERATION CONVERTER',
    acceleration_converter_description: 'विभिन्न इकाइयों को बदलें।',
    area_converter_label: 'AREA CONVERTER',
    area_converter_description: 'क्षेत्र की इकाइयों को बदलें।',
    fuel_converter_label: 'FUEL CONVERTER',
    fuel_converter_description: 'ईंधन दक्षता बदलें।',
    pressure_converter_label: 'PRESSURE CONVERTER',
    pressure_converter_description: 'दबाव की इकाइयों को बदलें।',
    fuel_cost_calculator_label: 'FUEL COST CALCULATOR',
    fuel_cost_calculator_description: 'यात्रा के ईंधन का अनुमान लगाएं।',
    interest_calculator_label: 'INTEREST CALCULATOR',
    interest_calculator_description: 'साधारण और चक्रवृद्धि ब्याज।',
    sales_tax_calculator_label: 'SALES TAX CALCULATOR',
    sales_tax_calculator_description: 'टैक्स और कुल कीमत देखें।',
    color_picker_label: 'COLOR PICKER STUDIO',
    color_picker_description: 'कंट्रास्ट चेकर के साथ पेशेवर कलर पैलेट जेनरेटर।',
    search_tools_placeholder: 'उपकरण खोजें...',
    no_tools_found: 'कोई उपकरण नहीं मिला',
    remove_background_label: 'BACKGROUND REMOVER',
    remove_background_description: 'छवि से बैकग्राउंड तुरंत हटाएं।',
    remove_signature_label: 'SIGNATURE BG REMOVER',
    remove_signature_description: 'फोटो से सिग्नेचर निकालें।',
    enhance_photo_label: 'PHOTO ENHANCER',
    enhance_photo_description: 'फोटो क्वालिटी बेहतर करें।',
    image_to_text_label: 'IMAGE TO TEXT (OCR)',
    image_to_text_description: 'इमेज से टेक्स्ट निकालें।',
    text_to_pdf_label: 'TEXT TO PDF',
    text_to_pdf_description: 'टेक्स्ट को PDF में बदलें।',
    barcode_generator_label: 'BARCODE GENERATOR',
    barcode_generator_description: 'तुरंत विभिन्न फॉर्मेट में स्कैनेबल बारकोड बनाएं।',
    qr_code_generator_label: 'QR CODE GENERATOR',
    qr_code_generator_description: 'लोगो और ग्रेडिएंट के साथ कस्टम QR कोड तुरंत बनाएं।',
    ai_upscaler_label: 'AI UPSCALER',
    ai_upscaler_description: 'AI का उपयोग करके छवियों को 2x और 4x अपस्केल करें।',
    privacy_policy: 'गोपनीयता नीति',
    terms_of_service: 'सेवा की शर्तें',
  },
  es: {
    site_title: 'GR7 Herramientas Hub',
    welcome: 'Bienvenido a GR7 Herramientas Hub',
    english: 'Inglés',
    hindi: 'Hindi',
    spanish: 'Español',
    language: 'Idioma',
    home: 'Inicio',
    tagline: 'Herramientas de navegador rápidas, privadas y profesionales.',
    image_tools: 'IMAGE TOOLS',
    pdf_tools: 'PDF TOOLS',
    file_tools: 'FILE TOOLS',
    audio_tools: 'AUDIO TOOLS',
    video_tools: 'VIDEO TOOLS',
    calculator_pro: 'CALCULATORS',
    converter_tools: 'CONVERTERS',
    image_compress_label: 'IMAGE COMPRESS',
    image_compress_description: 'Reduce el tamaño sin perder calidad.',
    resize_image_label: 'IMAGE RESIZER',
    resize_image_description: 'Cambia dimensiones rápidamente.',
    signature_resizer_label: 'SIGNATURE RESIZER',
    signature_resizer_description: 'Ajuste el tamaño de la firma a CM/Pixel y KB exactos.',
    crop_image_label: 'CROP IMAGE',
    crop_image_description: 'Recorta al tamaño perfecto.',
    passport_photo_label: 'PASSPORT PHOTO MAKER',
    passport_photo_description: 'Crea fotos profesionales al instante.',
    passport_date_name_label: 'ADD NAME & DATE TO PHOTO',
    passport_date_name_description: 'Agregue nombre y fecha a las fotos de pasaporte.',
    aadhaar_printer_label: 'AADHAAR CARD PRINTER',
    aadhaar_printer_description: 'Recorta y organiza para impresión.',
    image_to_jpg_label: 'IMAGE TO JPG',
    image_to_jpg_description: 'Convierte imágenes a JPG.',
    image_to_png_label: 'IMAGE TO PNG',
    image_to_png_description: 'Convierte imágenes a PNG.',
    image_to_pdf_label: 'IMAGE TO PDF',
    image_to_pdf_description: 'Convierte imágenes a un PDF.',
    html_to_pdf_label: 'HTML TO PDF',
    html_to_pdf_description: 'Convierte código HTML a PDF.',
    pdf_to_image_label: 'PDF TO IMAGE',
    pdf_to_image_description: 'Extrae páginas como imágenes.',
    compress_pdf_label: 'PDF COMPRESS',
    compress_pdf_description: 'Reduce el tamaño del PDF.',
    merge_pdf_label: 'MERGE PDF',
    merge_pdf_description: 'Combina varios PDF en uno.',
    split_pdf_label: 'SPLIT PDF',
    split_pdf_description: 'Extrae páginas de un PDF.',
    rotate_pdf_label: 'ROTATE PDF',
    rotate_pdf_description: 'Rota páginas de PDF permanentemente.',
    organize_pdf_label: 'ORGANIZE PDF',
    organize_pdf_description: 'Elimina, reordena y rota páginas visualmente.',
    crop_pdf_label: 'CROP PDF',
    crop_pdf_description: 'Recorta páginas de PDF.',
    edit_pdf_label: 'EDIT PDF',
    edit_pdf_description: 'Añade texto, imágenes y reorganiza páginas en tu PDF.',
    document_scan_label: 'DOCUMENT SCAN',
    document_scan_description: 'Escáner premium con filtros BW PRO y Color.',
    unlock_pdf_label: 'UNLOCK PDF',
    unlock_pdf_description: 'Elimina contraseña de PDF.',
    lock_pdf_label: 'PDF LOCKER',
    lock_pdf_description: 'Protege PDF con AES.',
    add_watermark_label: 'ADD WATERMARK',
    add_watermark_description: 'Añade texto al PDF.',
    add_page_numbers_label: 'ADD PAGE NUMBERS',
    add_page_numbers_description: 'Inserta números en PDF.',
    audio_converter_label: 'Convertidor de audio',
    audio_converter_description: 'Convierte entre MP3, WAV, OGG y M4A al instante.',
    audio_merger_label: 'Fusión de audio',
    audio_merger_description: 'Combine varias pistas de audio en un solo archivo.',
    video_to_mp3_label: 'VIDEO TO MP3',
    video_to_mp3_description: 'Extrae audio de alta calidad de videos.',
    mp3_cutter_label: 'MP3 CUTTER & AUDIO STUDIO',
    mp3_cutter_description: 'Trim, cut and enhance audio files with precise waveform control.',
    create_zip_label: 'CREATE ZIP',
    create_zip_description: 'Combina archivos en un zip.',
    unzip_file_label: 'UNZIP FILE',
    unzip_file_description: 'Extrae archivos de un zip.',
    standard_calculator_label: 'STANDARD CALCULATOR',
    standard_calculator_description: 'Para cálculos diarios.',
    loan_emi_calculator_label: 'LOAN & EMI CALCULATOR',
    loan_emi_calculator_description: 'Calcula pagos de préstamos.',
    mortgage_calculator_label: 'MORTGAGE CALCULATOR',
    mortgage_calculator_description: 'Estimador integral de préstamos e intereses para viviendas.',
    age_calculator_label: 'AGE CALCULATOR',
    age_calculator_description: 'Descubre tu perfil de edad.',
    percentage_calculator_label: 'PERCENTAGE CALCULATOR',
    percentage_calculator_description: 'Calcula porcentajes rápido.',
    gst_calculator_label: 'GST CALCULATOR',
    gst_calculator_description: 'Calcule GST agregado o eliminado.',
    gst_invoice_label: 'GST INVOICE GENERATOR',
    gst_invoice_description: 'Generar facturas compatibles con GST al instante.',
    salary_slip_label: 'SALARY SLIP GENERATOR',
    salary_slip_description: 'Cree recibos de sueldo profesionales en A4 para empleados al instante.',
    sip_calculator_label: 'SIP CALCULATOR',
    sip_calculator_description: 'Calcule rendimientos de sus fondos mutuos.',
    fd_rd_calculator_label: 'FD & RD CALCULATOR',
    fd_rd_calculator_description: 'Calcule los rendimientos de los depósitos fijos y recurrentes.',
    income_tax_calculator_label: 'INCOME TAX CALCULATOR',
    income_tax_calculator_description: 'Calcule impuestos basados en el régimen indio.',
    acceleration_converter_label: 'ACCELERATION CONVERTER',
    acceleration_converter_description: 'Convierte unidades de aceleración.',
    area_converter_label: 'AREA CONVERTER',
    area_converter_description: 'Convierte unidades de área.',
    fuel_converter_label: 'FUEL CONVERTER',
    fuel_converter_description: 'Convierte eficiencia de combustible.',
    pressure_converter_label: 'PRESSURE CONVERTER',
    pressure_converter_description: 'Convierte unidades de presión.',
    fuel_cost_calculator_label: 'FUEL COST CALCULATOR',
    fuel_cost_calculator_description: 'Estima gastos de viaje.',
    interest_calculator_label: 'INTEREST CALCULATOR',
    interest_calculator_description: 'Interés simple y compuesto.',
    sales_tax_calculator_label: 'SALES TAX CALCULATOR',
    sales_tax_calculator_description: 'Calcula impuesto y total.',
    color_picker_label: 'COLOR PICKER STUDIO',
    color_picker_description: 'Generador de paletas profesional con verificador de contraste.',
    search_tools_placeholder: 'Buscar herramientas...',
    no_tools_found: 'No se encontraron herramientas',
    remove_background_label: 'BACKGROUND REMOVER',
    remove_background_description: 'Quita fondo de imágenes automáticamente.',
    remove_signature_label: 'SIGNATURE BG REMOVER',
    remove_signature_description: 'Extrae firmas de fotos.',
    enhance_photo_label: 'PHOTO ENHANCER',
    enhance_photo_description: 'Mejora calidad profesionalmente.',
    image_to_text_label: 'IMAGE TO TEXT (OCR)',
    image_to_text_description: 'Extrae texto localmente.',
    text_to_pdf_label: 'TEXT TO PDF',
    text_to_pdf_description: 'Convierte texto a PDF.',
    barcode_generator_label: 'BARCODE GENERATOR',
    barcode_generator_description: 'Cree códigos de barras escaneables en varios formatos al instante.',
    qr_code_generator_label: 'QR CODE GENERATOR',
    qr_code_generator_description: 'Genere códigos QR personalizados con logotipos y degradados al instante.',
    ai_upscaler_label: 'AI UPSCALER',
    ai_upscaler_description: 'Aumente la escala de las imágenes a 2x y 4x utilizando la IA del navegador.',
    privacy_policy: 'Política de Privacidad',
    terms_of_service: 'Términos de Servicio',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    const langDict = (translations[language] || translations['en']) as Record<string, string>;
    return langDict[key] || key;
  };

  const value = {
    language,
    setLanguage,
    t
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
