
'use client';

import React, { createContext, useState, useContext, ReactNode } from 'react';

type Language = 'en' | 'hi' | 'es';

type LanguageContextType = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
};

const translations = {
  en: {
    welcome: 'Welcome to GRs Multi Tools Kit hub',
    english: 'English',
    hindi: 'Hindi',
    spanish: 'Spanish',
    language: 'Language',
    tagline: 'Your all-in-one tool for file manipulation. Fast, private, and easy to use.',
    image_tools: 'Image Tools',
    pdf_tools: 'PDF Tools',
    file_tools: 'File Tools',
    calculator_pro: 'Calculator Pro',
    converter_tools: 'Converters',
    image_compress_label: 'Image Compress',
    image_compress_description: 'Reduce image file size without losing quality.',
    resize_image_label: 'Resize Image',
    resize_image_description: 'Change the dimensions of your image quickly.',
    crop_image_label: 'Crop Image',
    crop_image_description: 'Easily crop your images to the perfect size.',
    image_to_jpg_label: 'Image to JPG',
    image_to_jpg_description: 'Convert various image formats to JPG.',
    image_to_png_label: 'Image to PNG',
    image_to_png_description: 'Convert various image formats to PNG.',
    image_to_pdf_label: 'Image to PDF',
    image_to_pdf_description: 'Convert images into a single PDF file.',
    pdf_to_image_label: 'PDF to Image',
    pdf_to_image_description: 'Extract all pages from a PDF as images.',
    compress_pdf_label: 'Compress PDF',
    compress_pdf_description: 'Reduce the file size of your PDF documents.',
    merge_pdf_label: 'Merge PDF',
    merge_pdf_description: 'Combine multiple PDFs into one document.',
    edit_pdf_label: 'Edit PDF',
    edit_pdf_description: 'Add text, shapes, and annotations to a PDF.',
    split_pdf_label: 'Split PDF',
    split_pdf_description: 'Extract specific pages from a PDF.',
    crop_pdf_label: 'Crop PDF',
    crop_pdf_description: 'Crop the visible area of PDF pages.',
    scan_to_pdf_label: 'Scan to PDF',
    scan_to_pdf_description: 'Scan documents directly to a PDF file.',
    protect_pdf_label: 'Protect PDF',
    protect_pdf_description: 'Add a password to your PDF.',
    unlock_pdf_label: 'Unlock PDF',
    unlock_pdf_description: 'Remove password protection from a PDF.',
    add_watermark_label: 'Add Watermark',
    add_watermark_description: 'Add a text or image watermark to your PDF.',
    create_zip_label: 'Create Zip',
    create_zip_description: 'Combine multiple files into a single zip archive.',
    unzip_file_label: 'Unzip File',
    unzip_file_description: 'Extract files from a zip archive.',
    about_shrinkray_title: 'About GRs Multi Tools Kit hub',
    about_detailed_description: 'All processing is done directly in your browser. No data is ever uploaded to our servers, ensuring your files remain completely private.',
    developed_by: 'Developed by',
    send_feedback: 'Send Feedback',
    about_tooltip: 'About',
    standard_calculator_label: 'Standard Calculator',
    standard_calculator_description: 'For your everyday calculations.',
    loan_emi_calculator_label: 'Loan & EMI Calculator',
    loan_emi_calculator_description: 'Calculate your loan payments with ease.',
    age_calculator_label: 'Age Calculator',
    age_calculator_description: 'Find out your exact age in years, months, and days.',
    percentage_calculator_label: 'Percentage Calculator',
    percentage_calculator_description: 'Quickly calculate percentages.',
    acceleration_converter_label: 'Acceleration Converter',
    acceleration_converter_description: 'Convert between different units of acceleration.',
    area_converter_label: 'Area Converter',
    area_converter_description: 'Convert between different units of area.',
    fuel_converter_label: 'Fuel Consumption Converter',
    fuel_converter_description: 'Convert between different fuel efficiency units.',
    currency_converter_label: 'Currency Converter',
    currency_converter_description: 'Convert between major world currencies.',
    pressure_converter_label: 'Pressure Converter',
    pressure_converter_description: 'Convert between different units of pressure.',
  },
  hi: {
    welcome: 'जीआरएस मल्टी टूल्स किट हब में आपका स्वागत है',
    english: 'अंग्रेज़ी',
    hindi: 'हिंदी',
    spanish: 'स्पेनिश',
    language: 'भाषा',
    tagline: 'फ़ाइल हेरफेर के लिए आपका ऑल-इन-वन टूल। तेज़, निजी और उपयोग में आसान।',
    image_tools: 'छवि उपकरण',
    pdf_tools: 'पीडीएफ उपकरण',
    file_tools: 'फ़ाइल उपकरण',
    calculator_pro: 'कैलकुलेटर प्रो',
    converter_tools: 'कन्वर्टर्स',
    image_compress_label: 'छवि संपीड़ित करें',
    image_compress_description: 'गुणवत्ता खोए बिना छवि फ़ाइल का आकार कम करें।',
    resize_image_label: 'छवि का आकार बदलें',
    resize_image_description: 'अपनी छवि के आयामों को तुरंत बदलें।',
    crop_image_label: 'छवि काटें',
    crop_image_description: 'आसानी से अपनी छवियों को सही आकार में काटें।',
    image_to_jpg_label: 'छवि को जेपीजी में बदलें',
    image_to_jpg_description: 'विभिन्न छवि प्रारूपों को जेपीजी में बदलें।',
    image_to_png_label: 'छवि को पीएनजी में बदलें',
    image_to_png_description: 'विभिन्न छवि प्रारूपों को पीएनजी में बदलें।',
    image_to_pdf_label: 'छवि को पीडीएफ में बदलें',
    image_to_pdf_description: 'छवियों को एक ही पीडीएफ फाइल में बदलें।',
    pdf_to_image_label: 'पीडीएफ को छवि में बदलें',
    pdf_to_image_description: 'पीडीएफ से सभी पृष्ठों को छवियों के रूप में निकालें।',
    compress_pdf_label: 'पीडीएफ संपीड़ित करें',
    compress_pdf_description: 'अपने पीडीएफ दस्तावेजों का फ़ाइल आकार कम करें।',
    merge_pdf_label: 'पीडीएफ मिलाएं',
    merge_pdf_description: 'कई पीडीएफ को एक दस्तावेज़ में मिलाएं।',
    edit_pdf_label: 'पीडीएफ संपादित करें',
    edit_pdf_description: 'पीडीएफ में टेक्स्ट, आकार और एनोटेशन जोड़ें।',
    split_pdf_label: 'पीडीएफ विभाजित करें',
    split_pdf_description: 'पीडीएफ से विशिष्ट पृष्ठ निकालें।',
    crop_pdf_label: 'पीडीएफ काटें',
    crop_pdf_description: 'पीडीएफ पृष्ठों के दृश्य क्षेत्र को काटें।',
    scan_to_pdf_label: 'पीडीएफ में स्कैन करें',
    scan_to_pdf_description: 'दस्तावेजों को सीधे पीडीएफ फाइल में स्कैन करें।',
    protect_pdf_label: 'पीडीएफ सुरक्षित करें',
    protect_pdf_description: 'अपने पीडीएफ में एक पासवर्ड जोड़ें।',
    unlock_pdf_label: 'पीडीएफ अनलॉक करें',
    unlock_pdf_description: 'पीडीएफ से पासवर्ड सुरक्षा हटाएं।',
    add_watermark_label: 'वॉटरमार्क जोड़ें',
    add_watermark_description: 'अपने पीडीएफ में टेक्स्ट या छवि वॉटरमार्क जोड़ें।',
    create_zip_label: 'ज़िप बनाएं',
    create_zip_description: 'कई फ़ाइलों को एक ज़िप संग्रह में मिलाएं।',
    unzip_file_label: 'फ़ाइल अनज़िप करें',
    unzip_file_description: 'एक ज़िप संग्रह से फ़ाइलें निकालें।',
    about_shrinkray_title: 'जीआरएस मल्टी टूल्स किट हब के बारे में',
    about_detailed_description: 'सभी प्रोसेसिंग सीधे आपके ब्राउज़र में की जाती है। हमारे सर्वर पर कभी कोई डेटा अपलोड नहीं किया जाता है, यह सुनिश्चित करते हुए कि आपकी फाइलें पूरी तरह से निजी रहें।',
    developed_by: 'द्वारा विकसित',
    send_feedback: 'प्रतिक्रिया भेजें',
    about_tooltip: 'बारे में',
    standard_calculator_label: 'मानक कैलकुलेटर',
    standard_calculator_description: 'आपकी रोजमर्रा की गणना के लिए।',
    loan_emi_calculator_label: 'ऋण और ईएमआई कैलकुलेटर',
    loan_emi_calculator_description: 'आसानी से अपने ऋण भुगतान की गणना करें।',
    age_calculator_label: 'आयु कैलकुलेटर',
    age_calculator_description: 'वर्षों, महीनों और दिनों में अपनी सटीक आयु का पता लगाएं।',
    percentage_calculator_label: 'प्रतिशत कैलकुलेटर',
    percentage_calculator_description: 'जल्दी से प्रतिशत की गणना करें।',
    acceleration_converter_label: 'त्वरण कनवर्टर',
    acceleration_converter_description: 'त्वरण की विभिन्न इकाइयों के बीच कनवर्ट करें।',
    area_converter_label: 'क्षेत्र कनवर्टर',
    area_converter_description: 'क्षेत्र की विभिन्न इकाइयों के बीच कनवर्ट करें।',
    fuel_converter_label: 'ईंधन खपत कनवर्टर',
    fuel_converter_description: 'विभिन्न ईंधन दक्षता इकाइयों के बीच कनवर्ट करें।',
    currency_converter_label: 'मुद्रा परिवर्तक',
    currency_converter_description: 'प्रमुख विश्व मुद्राओं के बीच कनवर्ट करें।',
    pressure_converter_label: 'दबाव कनवर्टर',
    pressure_converter_description: 'दबाव की विभिन्न इकाइयों के बीच कनवर्ट करें।',
  },
  es: {
    welcome: 'Bienvenido a GRs Multi Tools Kit hub',
    english: 'Inglés',
    hindi: 'Hindi',
    spanish: 'Español',
    language: 'Idioma',
    tagline: 'Su herramienta todo en uno para la manipulación de archivos. Rápido, privado y fácil de usar.',
    image_tools: 'Herramientas de imagen',
    pdf_tools: 'Herramientas de PDF',
    file_tools: 'Herramientas de Archivo',
    calculator_pro: 'Calculadora Pro',
    converter_tools: 'Convertidores',
    image_compress_label: 'Comprimir imagen',
    image_compress_description: 'Reduce el tamaño del archivo de imagen sin perder calidad.',
    resize_image_label: 'Redimensionar imagen',
    resize_image_description: 'Cambia las dimensiones de tu imagen rápidamente.',
    crop_image_label: 'Recortar imagen',
    crop_image_description: 'Recorta fácilmente tus imágenes al tamaño perfecto.',
    image_to_jpg_label: 'Imagen a JPG',
    image_to_jpg_description: 'Convierte varios formatos de imagen a JPG.',
    image_to_png_label: 'Imagen a PNG',
    image_to_png_description: 'Convierte varios formatos de imagen a PNG.',
    image_to_pdf_label: 'Imagen a PDF',
    image_to_pdf_description: 'Convierte imágenes en un solo archivo PDF.',
    pdf_to_image_label: 'PDF a imagen',
    pdf_to_image_description: 'Extrae todas las páginas de un PDF como imágenes.',
    compress_pdf_label: 'Comprimir PDF',
    compress_pdf_description: 'Reduce el tamaño de archivo de tus documentos PDF.',
    merge_pdf_label: 'Unir PDF',
    merge_pdf_description: 'Combina varios PDF en un solo documento.',
    edit_pdf_label: 'Editar PDF',
    edit_pdf_description: 'Agrega texto, formas y anotaciones a un PDF.',
    split_pdf_label: 'Dividir PDF',
    split_pdf_description: 'Extrae páginas específicas de un PDF.',
    crop_pdf_label: 'Recortar PDF',
    crop_pdf_description: 'Recorta el área visible de las páginas PDF.',
    scan_to_pdf_label: 'Escanear a PDF',
    scan_to_pdf_description: 'Escanea documentos directamente a un archivo PDF.',
    protect_pdf_label: 'Proteger PDF',
    protect_pdf_description: 'Agrega una contraseña a tu PDF.',
    unlock_pdf_label: 'Desbloquear PDF',
    unlock_pdf_description: 'Elimina la protección por contraseña de un PDF.',
    add_watermark_label: 'Añadir marca de agua',
    add_watermark_description: 'Agrega una marca de agua de texto o imagen a tu PDF.',
    create_zip_label: 'Crear Zip',
    create_zip_description: 'Combina varios archivos en un solo archivo zip.',
    unzip_file_label: 'Descomprimir Archivo',
    unzip_file_description: 'Extrae archivos de un archivo zip.',
    about_shrinkray_title: 'Acerca de GRs Multi Tools Kit hub',
    about_detailed_description: 'Todo el procesamiento se realiza directamente en su navegador. Nunca se cargan datos en nuestros servidores, lo que garantiza que sus archivos permanezcan completamente privados.',
    developed_by: 'Desarrollado por',
    send_feedback: 'Enviar comentarios',
    about_tooltip: 'Acerca de',
    standard_calculator_label: 'Calculadora estándar',
    standard_calculator_description: 'Para tus cálculos diarios.',
    loan_emi_calculator_label: 'Calculadora de préstamos y EMI',
    loan_emi_calculator_description: 'Calcule los pagos de su préstamo con facilidad.',
    age_calculator_label: 'Calculadora de edad',
    age_calculator_description: 'Descubra su edad exacta en años, meses y días.',
    percentage_calculator_label: 'Calculadora de porcentaje',
    percentage_calculator_description: 'Calcular porcentajes rápidamente.',
    acceleration_converter_label: 'Convertidor de Aceleración',
    acceleration_converter_description: 'Convierte entre diferentes unidades de aceleración.',
    area_converter_label: 'Convertidor de Área',
    area_converter_description: 'Convierte entre diferentes unidades de área.',
    fuel_converter_label: 'Convertidor de Consumo de Combustible',
    fuel_converter_description: 'Convierte entre diferentes unidades de eficiencia de combustible.',
    currency_converter_label: 'Convertidor de Divisas',
    currency_converter_description: 'Convierte entre las principales monedas del mundo.',
    pressure_converter_label: 'Convertidor de Presión',
    pressure_converter_description: 'Convierte entre diferentes unidades de presión.',
  },
};


const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    const langDict = translations[language] as Record<string, string>;
    return langDict[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
