'use client';

import React, { createContext, useState, useContext, ReactNode } from 'react';

type Language = 'en' | 'hi' | 'es';

type LanguageContextType = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
};

const translations = {
  en: {
    site_title: 'GR7 Tools Hub',
    welcome: 'Welcome to GR7 Tools Hub',
    english: 'English',
    hindi: 'Hindi',
    spanish: 'Spanish',
    language: 'Language',
    home: 'Home',
    tagline: 'Fast, private, and professional browser tools.',
    image_tools: 'Image Tools',
    pdf_tools: 'PDF Tools',
    file_tools: 'File Tools',
    calculator_pro: 'Calculator Pro',
    converter_tools: 'Converters',
    image_compress_label: 'Image Compress',
    image_compress_description: 'Reduce image file size without losing quality.',
    resize_image_label: 'Resize Image',
    resize_image_description: 'Change the dimensions of your image quickly.',
    crop_image_label: 'Crop Image',
    crop_image_description: 'Easily crop your images to the perfect size.',
    passport_photo_label: 'Passport Photo Maker',
    passport_photo_description: 'Create professional passport-sized photos instantly.',
    aadhaar_printer_label: 'Aadhaar Card Printer',
    aadhaar_printer_description: 'Auto-crop and arrange e-Aadhaar for easy printing.',
    image_to_jpg_label: 'Image to JPG',
    image_to_jpg_description: 'Convert various image formats to JPG.',
    image_to_png_label: 'Image to PNG',
    image_to_png_description: 'Convert various image formats to PNG.',
    image_to_pdf_label: 'Image to PDF',
    image_to_pdf_description: 'Convert images into a single PDF file.',
    html_to_pdf_label: 'HTML to PDF',
    html_to_pdf_description: 'Convert raw HTML code into a PDF document.',
    pdf_to_image_label: 'PDF to Image',
    pdf_to_image_description: 'Extract all pages from a PDF as images.',
    compress_pdf_label: 'Compress PDF',
    compress_pdf_description: 'Reduce the file size of your PDF documents.',
    merge_pdf_label: 'Merge PDF',
    merge_pdf_description: 'Combine multiple PDFs into one document.',
    split_pdf_label: 'Split PDF',
    split_pdf_description: 'Extract specific pages from a PDF.',
    crop_pdf_label: 'Crop PDF',
    crop_pdf_description: 'Crop the visible area of PDF pages.',
    scan_to_pdf_label: 'Scan to PDF',
    scan_to_pdf_description: 'Scan documents directly to a PDF file.',
    document_scan_label: 'AI Document Scan',
    document_scan_description: 'Premium AI scanner with BW PRO and Magic Color filters.',
    unlock_pdf_label: 'Unlock PDF',
    unlock_pdf_description: 'Remove password protection from a PDF.',
    lock_pdf_label: 'Vault PDF Locker',
    lock_pdf_description: 'Protect your PDF with secure AES encryption.',
    add_watermark_label: 'Add Watermark',
    add_watermark_description: 'Add a text watermark to your PDF.',
    add_page_numbers_label: 'Add Page Numbers',
    add_page_numbers_description: 'Insert page numbers into your PDF document.',
    word_to_pdf_label: 'Word to PDF',
    word_to_pdf_description: 'Convert DOCX documents to professional PDF.',
    create_zip_label: 'Create Zip',
    create_zip_description: 'Combine multiple files into a single zip.',
    unzip_file_label: 'Unzip File',
    unzip_file_description: 'Extract files from a zip archive.',
    standard_calculator_label: 'Standard Calculator',
    standard_calculator_description: 'For your everyday calculations.',
    loan_emi_calculator_label: 'Loan & EMI Calculator',
    loan_emi_calculator_description: 'Calculate your loan payments ease.',
    age_calculator_label: 'Age Calculator',
    age_calculator_description: 'Find out your exact age profile.',
    percentage_calculator_label: 'Percentage Calculator',
    percentage_calculator_description: 'Quickly calculate percentages.',
    acceleration_converter_label: 'Acceleration Converter',
    acceleration_converter_description: 'Convert between different units.',
    area_converter_label: 'Area Converter',
    area_converter_description: 'Convert between different area units.',
    fuel_converter_label: 'Fuel Consumption Converter',
    fuel_converter_description: 'Convert between efficiency units.',
    pressure_converter_label: 'Pressure Converter',
    pressure_converter_description: 'Convert between different units.',
    fuel_cost_calculator_label: 'Fuel Cost Calculator',
    fuel_cost_calculator_description: 'Estimate trip fuel expenses.',
    interest_calculator_label: 'Interest Calculator',
    interest_calculator_description: 'Simple and compound interest.',
    sales_tax_calculator_label: 'Sales Tax Calculator',
    sales_tax_calculator_description: 'Calculate tax and total price.',
    search_tools_placeholder: 'Search for tools...',
    no_tools_found: 'No tools found',
    remove_background_label: 'Remove Background',
    remove_background_description: 'Automatically remove background from any image.',
    remove_signature_label: 'Signature BG Remover',
    remove_signature_description: 'Extract clean signatures from paper photos.',
    enhance_photo_label: 'Enhance Photo',
    enhance_photo_description: 'Improve photo quality professionally.',
    image_to_text_label: 'Image to Text (OCR)',
    image_to_text_description: 'Extract text from any image locally.',
    text_to_pdf_label: 'Text to PDF',
    text_to_pdf_description: 'Convert plain text into a PDF document.',
    privacy_policy: 'Privacy Policy',
    terms_of_service: 'Terms of Service',
  },
  hi: {
    site_title: 'GR7 टूल्स हब',
    welcome: 'GR7 टूल्स हब में आपका स्वागत है',
    english: 'अंग्रेज़ी',
    hindi: 'हिंदी',
    spanish: 'स्पेनिश',
    language: 'भाषा',
    home: 'होम',
    tagline: 'तेज़, निजी और पेशेवर ब्राउज़र उपकरण।',
    image_tools: 'इमेज टूल्स',
    pdf_tools: 'पीडीएफ टूल्स',
    file_tools: 'फ़ाइल टूल्स',
    calculator_pro: 'कैलकुलेटर प्रो',
    converter_tools: 'कन्वर्टर्स',
    image_compress_label: 'छवि संपीड़ित',
    image_compress_description: 'गुणवत्ता खोए बिना आकार कम करें।',
    resize_image_label: 'आकार बदलें',
    resize_image_description: 'छवि के आयाम तुरंत बदलें।',
    crop_image_label: 'इमेज क्रॉप',
    crop_image_description: 'छवियों को सही आकार में काटें।',
    passport_photo_label: 'पासपोर्ट फोटो मेकर',
    passport_photo_description: 'प्रोफेशनल पासपोर्ट फोटो तुरंत बनाएं।',
    aadhaar_printer_label: 'आधार कार्ड प्रिंटर',
    aadhaar_printer_description: 'ई-आधार को व्यवस्थित और प्रिंट करें।',
    image_to_jpg_label: 'इमेज से JPG',
    image_to_jpg_description: 'छवियों को JPG में बदलें।',
    image_to_png_label: 'इमेज से PNG',
    image_to_png_description: 'छवियों को PNG में बदलें।',
    image_to_pdf_label: 'इमेज से PDF',
    image_to_pdf_description: 'छवियों को एक पीडीएफ फाइल में बदलें।',
    html_to_pdf_label: 'HTML से PDF',
    html_to_pdf_description: 'HTML कोड को PDF में बदलें।',
    pdf_to_image_label: 'PDF से इमेज',
    pdf_to_image_description: 'PDF के पन्नों को इमेज में निकालें।',
    compress_pdf_label: 'PDF संपीड़ित',
    compress_pdf_description: 'PDF फ़ाइल का आकार कम करें।',
    merge_pdf_label: 'PDF जोड़ें',
    merge_pdf_description: 'कई PDF को एक में मिलाएं।',
    split_pdf_label: 'PDF विभाजित',
    split_pdf_description: 'PDF से विशिष्ट पन्ने निकालें।',
    crop_pdf_label: 'PDF क्रॉप',
    crop_pdf_description: 'PDF पन्नों को क्रॉप करें।',
    scan_to_pdf_label: 'PDF स्कैन करें',
    scan_to_pdf_description: 'दस्तावेजों को सीधे PDF में स्कैन करें।',
    document_scan_label: 'AI डॉक्यूमेंट स्कैन',
    document_scan_description: 'BW PRO और मैजिक कलर फिल्टर के साथ प्रीमियम स्कैनर।',
    unlock_pdf_label: 'PDF अनलॉक',
    unlock_pdf_description: 'PDF से पासवर्ड हटाएं।',
    lock_pdf_label: 'वॉल्ट PDF लॉकर',
    lock_pdf_description: 'PDF को पासवर्ड से सुरक्षित करें।',
    add_watermark_label: 'वॉटरमार्क जोड़ें',
    add_watermark_description: 'PDF में वॉटरमार्क टेक्स्ट जोड़ें।',
    add_page_numbers_label: 'पेज नंबर जोड़ें',
    add_page_numbers_description: 'PDF में पेज नंबर डालें।',
    word_to_pdf_label: 'Word से PDF',
    word_to_pdf_description: 'DOCX को प्रोफेशनल PDF में बदलें।',
    create_zip_label: 'ज़िप बनाएं',
    create_zip_description: 'कई फ़ाइलों को ज़िप में मिलाएं।',
    unzip_file_label: 'अनज़िप करें',
    unzip_file_description: 'ज़िप से फ़ाइलें निकालें।',
    standard_calculator_label: 'मानक कैलकुलेटर',
    standard_calculator_description: 'रोजमर्रा की गणना के लिए।',
    loan_emi_calculator_label: 'EMI कैलकुलेटर',
    loan_emi_calculator_description: 'ऋण भुगतान की गणना करें।',
    age_calculator_label: 'आयु कैलकुलेटर',
    age_calculator_description: 'अपनी सटीक आयु प्रोफाइल देखें।',
    percentage_calculator_label: 'प्रतिशत कैलकुलेटर',
    percentage_calculator_description: 'प्रतिशत की गणना करें।',
    acceleration_converter_label: 'त्वरण कनवर्टर',
    acceleration_converter_description: 'विभिन्न इकाइयों को बदलें।',
    area_converter_label: 'क्षेत्र कनवर्टर',
    area_converter_description: 'क्षेत्र की इकाइयों को बदलें।',
    fuel_converter_label: 'ईंधन कनवर्टर',
    fuel_converter_description: 'ईंधन दक्षता बदलें।',
    pressure_converter_label: 'दबाव कनवर्टer',
    pressure_converter_description: 'दबाव की इकाइयों को बदलें।',
    fuel_cost_calculator_label: 'ईंधन लागत',
    fuel_cost_calculator_description: 'यात्रा के ईंधन का अनुमान लगाएं।',
    interest_calculator_label: 'ब्याज कैलकुलेटर',
    interest_calculator_description: 'साधारण और चक्रवृद्धि ब्याज।',
    sales_tax_calculator_label: 'बिक्री कर कैलकुलेटर',
    sales_tax_calculator_description: 'टैक्स और कुल कीमत देखें।',
    search_tools_placeholder: 'उपकरण खोजें...',
    no_tools_found: 'कोई उपकरण नहीं मिला',
    remove_background_label: 'बैकग्राउंड हटाएं',
    remove_background_description: 'छवि से बैकग्राउंड तुरंत हटाएं।',
    remove_signature_label: 'सिग्नेचर रिमूवर',
    remove_signature_description: 'फोटो से सिग्नेचर निकालें।',
    enhance_photo_label: 'फोटो एनहांस',
    enhance_photo_description: 'फोटो क्वालिटी बेहतर करें।',
    image_to_text_label: 'इमेज से टेक्स्ट (OCR)',
    image_to_text_description: 'इमेज से टेक्स्ट निकालें।',
    text_to_pdf_label: 'टेक्स्ट से PDF',
    text_to_pdf_description: 'टेक्स्ट को PDF में बदलें।',
    privacy_policy: 'गोपनीयता नीति',
    terms_of_service: 'सेवा की शर्तें',
  },
  es: {
    site_title: 'GR7 Herramientas Hub',
    welcome: 'Bienvenido a GR7 Herramientas Hub',
    english: 'Inglés',
    hindi: 'Hindi',
    spanish: 'Español',
    language: 'Idioma',
    home: 'Inicio',
    tagline: 'Herramientas de navegador rápidas, privadas y profesionales.',
    image_tools: 'Imágenes',
    pdf_tools: 'PDF',
    file_tools: 'Archivos',
    calculator_pro: 'Calculadora Pro',
    converter_tools: 'Convertidores',
    image_compress_label: 'Comprimir Imagen',
    image_compress_description: 'Reduce el tamaño sin perder calidad.',
    resize_image_label: 'Redimensionar',
    resize_image_description: 'Cambia dimensiones rápidamente.',
    crop_image_label: 'Recortar Imagen',
    crop_image_description: 'Recorta al tamaño perfecto.',
    passport_photo_label: 'Fotos de Pasaporte',
    passport_photo_description: 'Crea fotos profesionales al instante.',
    aadhaar_printer_label: 'Impresora Aadhaar',
    aadhaar_printer_description: 'Recorta y organiza para impresión.',
    image_to_jpg_label: 'Imagen a JPG',
    image_to_jpg_description: 'Convierte imágenes a JPG.',
    image_to_png_label: 'Imagen a PNG',
    image_to_png_description: 'Convierte imágenes a PNG.',
    image_to_pdf_label: 'Imagen a PDF',
    image_to_pdf_description: 'Convierte imágenes a un PDF.',
    html_to_pdf_label: 'HTML a PDF',
    html_to_pdf_description: 'Convierte código HTML a PDF.',
    pdf_to_image_label: 'PDF a Imagen',
    pdf_to_image_description: 'Extrae páginas como imágenes.',
    compress_pdf_label: 'Comprimir PDF',
    compress_pdf_description: 'Reduce el tamaño del PDF.',
    merge_pdf_label: 'Unir PDF',
    merge_pdf_description: 'Combina varios PDF en uno.',
    split_pdf_label: 'Dividir PDF',
    split_pdf_description: 'Extrae páginas de un PDF.',
    crop_pdf_label: 'Recortar PDF',
    crop_pdf_description: 'Recorta páginas de PDF.',
    scan_to_pdf_label: 'Escanear a PDF',
    scan_to_pdf_description: 'Escanea directamente a PDF.',
    document_scan_label: 'Escaneo de Documentos AI',
    document_scan_description: 'Escáner premium con filtros BW PRO y Color.',
    unlock_pdf_label: 'Desbloquear PDF',
    unlock_pdf_description: 'Elimina contraseña de PDF.',
    lock_pdf_label: 'Locker de PDF',
    lock_pdf_description: 'Protege PDF con AES.',
    add_watermark_label: 'Marca de Agua',
    add_watermark_description: 'Añade texto al PDF.',
    add_page_numbers_label: 'Números de Página',
    add_page_numbers_description: 'Inserta números en PDF.',
    word_to_pdf_label: 'Word a PDF',
    word_to_pdf_description: 'Convierte DOCX a PDF profesional.',
    create_zip_label: 'Crear Zip',
    create_zip_description: 'Combina archivos en un zip.',
    unzip_file_label: 'Descomprimir',
    unzip_file_description: 'Extrae archivos de un zip.',
    standard_calculator_label: 'Calculadora Estándar',
    standard_calculator_description: 'Para cálculos diarios.',
    loan_emi_calculator_label: 'Calculadora de Préstamos',
    loan_emi_calculator_description: 'Calcula pagos de préstamos.',
    age_calculator_label: 'Calculadora de Edad',
    age_calculator_description: 'Descubre tu perfil de edad.',
    percentage_calculator_label: 'Porcentaje',
    percentage_calculator_description: 'Calcula porcentajes rápido.',
    acceleration_converter_label: 'Aceleración',
    acceleration_converter_description: 'Convierte unidades de aceleración.',
    area_converter_label: 'Área',
    area_converter_description: 'Convierte unidades de área.',
    fuel_converter_label: 'Consumo de Combustible',
    fuel_converter_description: 'Convierte eficiencia de combustible.',
    pressure_converter_label: 'Presión',
    pressure_converter_description: 'Convierte unidades de presión.',
    fuel_cost_calculator_label: 'Costo de Combustible',
    fuel_cost_calculator_description: 'Estima gastos de viaje.',
    interest_calculator_label: 'Interés',
    interest_calculator_description: 'Interés simple y compuesto.',
    sales_tax_calculator_label: 'Impuesto de Ventas',
    sales_tax_calculator_description: 'Calcula impuesto y total.',
    search_tools_placeholder: 'Buscar herramientas...',
    no_tools_found: 'No se encontraron herramientas',
    remove_background_label: 'Quitar Fondo',
    remove_background_description: 'Quita fondo de imágenes automáticamente.',
    remove_signature_label: 'Quitar Firma',
    remove_signature_description: 'Extrae firmas de fotos.',
    enhance_photo_label: 'Mejorar Foto',
    enhance_photo_description: 'Mejora calidad profesionalmente.',
    image_to_text_label: 'Imagen a Texto',
    image_to_text_description: 'Extrae texto localmente.',
    text_to_pdf_label: 'Texto a PDF',
    text_to_pdf_description: 'Convierte texto a PDF.',
    privacy_policy: 'Política de Privacidad',
    terms_of_service: 'Términos de Servicio',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    const langDict = (translations[language] || translations['en']) as Record<string, string>;
    return langDict[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
