"use client";

import { useState, useRef, useEffect, useCallback, type ChangeEvent } from 'react';
import { useToast } from '@/hooks/use-toast';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from '@/components/ui/card';
import { Textarea } from '@/components/ui/textarea';
import { 
    Download, 
    Loader2, 
    FileCode, 
    Eye, 
    Globe, 
    Zap, 
    ShieldCheck, 
    Smartphone, 
    UploadCloud, 
    Trash2, 
    Monitor,
    Sparkles,
    ChevronRight,
    SearchCode,
    X
} from 'lucide-react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { Badge } from '@/components/ui/badge';
import { Label } from '@/components/ui/label';
import { cn } from '@/lib/utils';

const initialHtml = `<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #333; line-height: 1.6; background: white; }
        .hero { background: linear-gradient(135deg, #5cbdb9 0%, #3aa39f 100%); color: white; padding: 40px; border-radius: 24px; margin-bottom: 30px; text-align: center; }
        h1 { margin: 0; font-size: 36px; letter-spacing: -1px; }
        .card { border: 2px solid #e2e8f0; padding: 25px; border-radius: 20px; margin-top: 20px; }
        .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 20px; }
    </style>
</head>
<body>
    <div class="hero">
        <h1>Live Web Document</h1>
        <p>This is a professional HTML to PDF preview.</p>
    </div>
    <div class="card">
        <h3>Why choose local rendering?</h3>
        <p>1. <strong>100% Private:</strong> Your code never leaves your device.<br>
           2. <strong>High DPI:</strong> Text remains sharp at any zoom level.<br>
           3. <strong>Instant:</strong> See changes as you type.</p>
    </div>
    <div class="footer">Generated by GR7 Tools Hub Studio</div>
</body>
</html>`;

type Stage = 'setup' | 'editor';

export default function HtmlToPdfConverter() {
    const { toast } = useToast();
    const [stage, setStage] = useState<Stage>('setup');
    const [htmlContent, setHtmlContent] = useState<string>(initialHtml);
    const [isGenerating, setIsGenerating] = useState(false);
    const [previewImage, setPreviewImage] = useState<string | null>(null);
    const [pdfBlob, setPdfBlob] = useState<Blob | null>(null);
    const [fileName, setFileName] = useState<string | null>(null);
    const [isDragOver, setIsDragOver] = useState(false);
    
    const previewRef = useRef<HTMLDivElement>(null);
    const fileInputRef = useRef<HTMLInputElement>(null);

    const generatePdf = useCallback(async () => {
        if (!htmlContent.trim() || !previewRef.current || stage !== 'editor') {
            return;
        }

        setIsGenerating(true);
        try {
            const canvas = await html2canvas(previewRef.current, {
                scale: 2,
                useCORS: true,
                logging: false,
                backgroundColor: '#FFFFFF',
                width: 794,
            });
            
            const imgData = canvas.toDataURL('image/jpeg', 0.92);
            setPreviewImage(imgData);

            const pdf = new jsPDF({
                orientation: canvas.width > canvas.height ? 'l' : 'p',
                unit: 'px',
                format: [canvas.width, canvas.height],
            });

            pdf.addImage(imgData, 'JPEG', 0, 0, canvas.width, canvas.height, undefined, 'FAST');
            setPdfBlob(pdf.output('blob'));
        } catch (error) {
            console.error("Live preview error:", error);
        } finally {
            setIsGenerating(false);
        }
    }, [htmlContent, stage]);

    useEffect(() => {
        if (stage === 'editor') {
            const timer = setTimeout(() => {
                generatePdf();
            }, 800); 
            return () => clearTimeout(timer);
        }
    }, [htmlContent, generatePdf, stage]);

    const handleFileUpload = (e: ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (file && (file.type === 'text/html' || file.name.endsWith('.html') || file.name.endsWith('.htm'))) {
            const reader = new FileReader();
            reader.onload = (event) => {
                const content = event.target?.result as string;
                setHtmlContent(content);
                setFileName(file.name);
                setStage('editor');
                toast({ title: 'File Uploaded', description: `${file.name} loaded into editor.` });
            };
            reader.readAsText(file);
        } else if (file) {
            toast({ variant: 'destructive', title: 'Invalid File', description: 'Please upload a .html or .htm file.' });
        }
    };

    const handleDownload = () => {
        if (!pdfBlob) return;
        const url = URL.createObjectURL(pdfBlob);
        const link = document.createElement('a');
        link.href = url;
        link.download = fileName ? `${fileName.split('.')[0]}.pdf` : 'web-document.pdf';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
        toast({ title: 'Success', description: 'Your professional PDF is ready.' });
    };

    const handleClear = () => {
        setHtmlContent('');
        setFileName(null);
        if (fileInputRef.current) fileInputRef.current.value = "";
    };

    const handleReset = () => {
        setStage('setup');
        setHtmlContent(initialHtml);
        setFileName(null);
        setPreviewImage(null);
        setPdfBlob(null);
    };

    if (stage === 'setup') {
        return (
            <Card className={cn(
                "w-full max-w-2xl text-center transition-all duration-300 bg-card/50 hover:border-primary/80 hover:shadow-2xl border-2 border-dashed mx-auto rounded-[2rem] overflow-hidden",
                isDragOver && "border-primary ring-4 ring-primary/20"
            )}
                onDragOver={(e) => { e.preventDefault(); setIsDragOver(true); }}
                onDragLeave={() => setIsDragOver(false)}
                onDrop={(e) => { e.preventDefault(); setIsDragOver(false); handleFileUpload({ target: { files: e.dataTransfer.files } } as any); }}
            >
                <CardHeader className="pt-8 md:pt-12">
                    <div className="mx-auto mb-4 grid size-16 md:size-20 place-items-center rounded-3xl bg-primary/10 text-primary">
                        <FileCode className="h-8 md:h-10 w-8 md:w-10" />
                    </div>
                    <CardTitle className="text-xl md:text-3xl font-black uppercase tracking-tight">HTML to PDF Studio</CardTitle>
                    <CardDescription className="text-[10px] md:text-sm uppercase font-bold opacity-60">Convert raw code or files into professional documents.</CardDescription>
                </CardHeader>
                <CardContent className="p-4 md:p-10">
                    <div
                        className="border-4 border-dashed border-muted-foreground/20 rounded-2xl md:rounded-[2rem] p-6 md:p-20 flex flex-col items-center justify-center space-y-6 cursor-pointer hover:bg-muted/30 transition-all group"
                        onClick={() => setStage('editor')}
                    >
                        <div className="relative">
                            <UploadCloud className="h-12 md:h-16 w-12 md:w-16 text-muted-foreground group-hover:text-primary transition-colors" />
                            <Zap className="absolute -top-2 -right-2 h-6 md:h-8 w-6 md:w-8 text-yellow-500 animate-pulse" />
                        </div>
                        <div className="text-center px-4">
                            <p className="text-lg md:text-xl font-bold uppercase tracking-tighter">Click to Start Editor</p>
                            <p className="text-[10px] md:text-xs text-muted-foreground mt-2 font-medium">Or drop an .html file here to begin extraction.</p>
                        </div>
                    </div>
                    <input ref={fileInputRef} type="file" className="hidden" accept=".html,.htm" onChange={handleFileUpload} />
                </CardContent>
                <CardFooter className="justify-center gap-4 md:gap-8 text-[8px] md:text-[10px] text-muted-foreground font-black uppercase tracking-widest pb-8 bg-muted/10 pt-6 px-4">
                    <div className="flex items-center gap-1.5"><ShieldCheck className="size-3 text-green-600" /> SECURE RAM</div>
                    <div className="flex items-center gap-1.5"><SearchCode className="size-3 text-primary" /> LIVE PREVIEW</div>
                    <div className="flex items-center gap-1.5"><Sparkles className="size-3 text-purple-500" /> 300 DPI HD</div>
                </CardFooter>
            </Card>
        );
    }
    
    return (
        <div className="w-full max-w-[1800px] mx-auto flex flex-col gap-6 md:gap-8 px-0 md:px-4 animate-in fade-in duration-500">
            {/* Hidden Sandbox for Rendering */}
            <div className="fixed top-0 -left-[5000px] -z-10 opacity-0 pointer-events-none">
                <div 
                    ref={previewRef} 
                    className="w-[794px] bg-white p-0 m-0 overflow-hidden" 
                    style={{ minHeight: '1123px' }}
                    dangerouslySetInnerHTML={{ __html: htmlContent }} 
                />
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 md:gap-8 items-start w-full">
                {/* Editor Section */}
                <div className="lg:col-span-5 flex flex-col gap-6 w-full">
                    <Card className="flex flex-col border-2 shadow-2xl rounded-2xl md:rounded-[2.5rem] overflow-hidden bg-white dark:bg-slate-950 flex-1 w-full border-primary/10">
                        <CardHeader className="bg-primary/5 border-b p-4 md:p-6 flex flex-row items-center justify-between">
                            <div className="flex items-center gap-3">
                                <div className="size-10 rounded-xl bg-primary/10 flex items-center justify-center text-primary">
                                    <FileCode className="size-5" />
                                </div>
                                <CardTitle className="text-lg md:text-xl font-black uppercase tracking-tighter">HTML Source</CardTitle>
                            </div>
                            <div className="flex gap-2">
                                <Button variant="ghost" size="icon" onClick={handleClear} className="h-8 w-8 text-destructive hover:bg-destructive/10">
                                    <Trash2 className="size-4" />
                                </Button>
                                <Button variant="ghost" size="icon" onClick={handleReset} className="h-8 w-8 text-muted-foreground hover:bg-muted">
                                    <X className="size-4" />
                                </Button>
                            </div>
                        </CardHeader>
                        <CardContent className="flex-1 flex flex-col gap-4 p-4 md:p-8">
                            <div className="flex items-center justify-between px-1">
                                <Label className="text-[10px] font-black uppercase tracking-widest text-muted-foreground flex items-center gap-2">
                                    <Globe className="size-3"/> Code Editor
                                </Label>
                                {fileName && <Badge variant="secondary" className="text-[9px] font-bold uppercase truncate max-w-[120px]">{fileName}</Badge>}
                            </div>
                            <Textarea
                                value={htmlContent}
                                onChange={(e) => setHtmlContent(e.target.value)}
                                placeholder="Paste your HTML code here..."
                                className="flex-1 min-h-[350px] md:min-h-[500px] font-mono text-[10px] md:text-xs leading-relaxed border-2 focus-visible:ring-primary rounded-xl md:rounded-2xl p-4 md:p-6 bg-slate-900 text-slate-100 custom-scrollbar w-full"
                            />
                        </CardContent>
                        <CardFooter className="p-4 md:p-6 bg-muted/10 border-t flex flex-col gap-4">
                            <Button 
                                variant="outline" 
                                className="w-full h-12 border-2 border-dashed border-primary/30 hover:border-primary font-black text-[10px] md:text-xs uppercase rounded-xl"
                                onClick={() => fileInputRef.current?.click()}
                            >
                                <UploadCloud className="mr-2 size-4" /> LOAD LOCAL FILE
                            </Button>
                            <input ref={fileInputRef} type="file" className="hidden" accept=".html,.htm" onChange={handleFileUpload} />
                        </CardFooter>
                    </Card>
                    
                    <div className="p-4 md:p-6 bg-primary/5 border-2 border-primary/10 rounded-2xl md:rounded-[2.5rem] flex gap-4 md:gap-5 items-center">
                        <div className="size-10 md:size-12 rounded-full bg-primary/10 flex items-center justify-center shrink-0">
                            <ShieldCheck className="size-5 md:size-6 text-primary" />
                        </div>
                        <div>
                            <p className="text-[10px] md:text-[11px] font-black text-primary uppercase tracking-tight">Privacy Guard Active</p>
                            <p className="text-[8px] md:text-[10px] text-muted-foreground font-medium leading-tight">All rendering happens 100% in your browser RAM.</p>
                        </div>
                    </div>
                </div>

                {/* PDF Live Result */}
                <Card className="lg:col-span-7 flex flex-col border-2 shadow-2xl rounded-2xl md:rounded-[2.5rem] overflow-hidden bg-slate-100 dark:bg-slate-900 border-primary/10 w-full min-h-[500px]">
                    <CardHeader className="bg-muted/30 border-b p-4 md:p-6 flex flex-row items-center justify-between px-4 md:px-8">
                        <div className="flex items-center gap-2">
                            <Eye className="size-4 text-primary" />
                            <CardTitle className="text-[10px] font-black uppercase tracking-widest text-muted-foreground">Live HD Preview</CardTitle>
                        </div>
                        <div className="flex items-center gap-3">
                            {isGenerating && <Loader2 className="size-3 animate-spin text-primary" />}
                            <Badge className="bg-green-600 text-white font-black text-[8px] md:text-[9px] uppercase tracking-widest px-3 py-1">HD READY</Badge>
                        </div>
                    </CardHeader>
                    <CardContent className="flex-1 p-4 md:p-8 lg:p-12 relative min-h-[400px] md:min-h-[500px] flex flex-col bg-slate-200 dark:bg-slate-800 shadow-inner overflow-y-auto max-h-[850px] custom-scrollbar">
                       {previewImage ? (
                            <div className="relative w-full shadow-2xl border-2 md:border-8 border-white bg-white rounded-sm mx-auto overflow-hidden animate-in zoom-in-95 duration-300">
                                <img
                                    src={previewImage}
                                    alt="Live PDF Preview"
                                    className="w-full h-auto block"
                                />
                                <div className="absolute top-0 right-0 p-2 opacity-20 pointer-events-none">
                                    <Badge variant="outline" className="text-[7px] md:text-[8px] font-black uppercase border-black">A4 CANVAS</Badge>
                                </div>
                            </div>
                        ) : (
                            <div className="flex-1 flex flex-col items-center justify-center text-center p-8 gap-4 md:gap-6">
                                <div className="relative">
                                    <Loader2 className="size-16 md:size-24 text-primary/10 animate-spin stroke-[4]" />
                                    <Monitor className="absolute inset-0 m-auto size-6 md:size-10 text-primary/20" />
                                </div>
                                <div className="space-y-2">
                                    <p className="text-xs md:text-sm font-black text-muted-foreground uppercase tracking-widest animate-pulse">Rendering Code...</p>
                                </div>
                            </div>
                        )}
                    </CardContent>
                    <CardFooter className="p-4 md:p-8 bg-white dark:bg-slate-950 border-t flex flex-col sm:flex-row gap-4">
                        <Button 
                            onClick={handleDownload} 
                            disabled={!pdfBlob || isGenerating} 
                            className="w-full h-14 md:h-20 text-base md:text-2xl font-black bg-primary hover:bg-primary/90 shadow-xl rounded-xl md:rounded-[1.5rem] group active:scale-95 transition-all"
                        >
                            <Download className="mr-3 h-5 w-5 md:h-8 md:w-8 group-hover:translate-y-0.5 transition-transform" />
                            <span className="hidden sm:inline">DOWNLOAD PROFESSIONAL PDF</span>
                            <span className="sm:hidden">DOWNLOAD PDF</span>
                        </Button>
                        <div className="flex items-center justify-center gap-4 text-[8px] md:text-[9px] font-black text-muted-foreground/40 uppercase tracking-[0.2em] w-full sm:w-auto">
                            <div className="flex items-center gap-1.5"><Smartphone className="size-3 text-primary" /> MOBILE SAFE</div>
                            <div className="flex items-center gap-1.5"><Zap className="size-3 text-yellow-500" /> NATIVE RENDER</div>
                        </div>
                    </CardFooter>
                </Card>
            </div>
        </div>
    );
}
