"use client";

import { useState, useRef, useEffect, useCallback, type ChangeEvent } from 'react';
import { useToast } from '@/hooks/use-toast';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from '@/components/ui/card';
import { Textarea } from '@/components/ui/textarea';
import { 
    Download, 
    Loader2, 
    FileCode, 
    Eye, 
    Globe, 
    Zap, 
    ShieldCheck, 
    Smartphone, 
    UploadCloud, 
    Trash2, 
    RefreshCcw,
    Monitor
} from 'lucide-react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { Badge } from '@/components/ui/badge';
import { Label } from '@/components/ui/label';

const initialHtml = `<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #333; line-height: 1.6; background: white; }
        .hero { background: linear-gradient(135deg, #6366f1 0%, #a855f7 100%); color: white; padding: 40px; border-radius: 24px; margin-bottom: 30px; text-align: center; }
        h1 { margin: 0; font-size: 36px; letter-spacing: -1px; }
        .card { border: 2px solid #e2e8f0; padding: 25px; border-radius: 20px; margin-top: 20px; }
        .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 20px; }
    </style>
</head>
<body>
    <div class="hero">
        <h1>Live Web Document</h1>
        <p>This is a professional HTML to PDF preview.</p>
    </div>
    <div class="card">
        <h3>Why choose local rendering?</h3>
        <p>1. <strong>100% Private:</strong> Your code never leaves your device.<br>
           2. <strong>High DPI:</strong> Text remains sharp at any zoom level.<br>
           3. <strong>Instant:</strong> See changes as you type.</p>
    </div>
    <div class="footer">Generated by GR7 Tools Hub Studio</div>
</body>
</html>`;

export default function HtmlToPdfConverter() {
    const { toast } = useToast();
    const [htmlContent, setHtmlContent] = useState<string>(initialHtml);
    const [isGenerating, setIsGenerating] = useState(false);
    const [previewImage, setPreviewImage] = useState<string | null>(null);
    const [pdfBlob, setPdfBlob] = useState<Blob | null>(null);
    const [fileName, setFileName] = useState<string | null>(null);
    const previewRef = useRef<HTMLDivElement>(null);
    const fileInputRef = useRef<HTMLInputElement>(null);

    const generatePdf = useCallback(async () => {
        if (!htmlContent.trim() || !previewRef.current) {
            setPreviewImage(null);
            setPdfBlob(null);
            return;
        }

        setIsGenerating(true);
        try {
            // High-DPI Capture for sharp text (2.0x scale)
            const canvas = await html2canvas(previewRef.current, {
                scale: 2,
                useCORS: true,
                logging: false,
                backgroundColor: '#FFFFFF',
                width: 794, // Standard A4 width pixels
            });
            
            const imgData = canvas.toDataURL('image/jpeg', 0.95);
            setPreviewImage(imgData);

            const pdf = new jsPDF({
                orientation: canvas.width > canvas.height ? 'l' : 'p',
                unit: 'px',
                format: [canvas.width, canvas.height],
            });

            pdf.addImage(imgData, 'JPEG', 0, 0, canvas.width, canvas.height, undefined, 'FAST');
            setPdfBlob(pdf.output('blob'));
        } catch (error) {
            console.error("Live HTML preview error:", error);
        } finally {
            setIsGenerating(false);
        }
    }, [htmlContent]);

    // Debounce live preview update
    useEffect(() => {
        const timer = setTimeout(() => {
            generatePdf();
        }, 800); 
        return () => clearTimeout(timer);
    }, [htmlContent, generatePdf]);

    const handleFileUpload = (e: ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (file && (file.type === 'text/html' || file.name.endsWith('.html') || file.name.endsWith('.htm'))) {
            const reader = new FileReader();
            reader.onload = (event) => {
                const content = event.target?.result as string;
                setHtmlContent(content);
                setFileName(file.name);
                toast({ title: 'File Uploaded', description: `${file.name} loaded into editor.` });
            };
            reader.readAsText(file);
        } else if (file) {
            toast({ variant: 'destructive', title: 'Invalid File', description: 'Please upload a .html or .htm file.' });
        }
    };

    const handleDownload = () => {
        if (!pdfBlob) return;
        const url = URL.createObjectURL(pdfBlob);
        const link = document.createElement('a');
        link.href = url;
        link.download = fileName ? `${fileName.split('.')[0]}.pdf` : 'web-document.pdf';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
        toast({ title: 'Success', description: 'Your professional PDF is ready.' });
    };

    const handleClear = () => {
        setHtmlContent('');
        setFileName(null);
        if (fileInputRef.current) fileInputRef.current.value = "";
    };
    
    return (
        <div className="w-full max-w-7xl flex flex-col gap-6 px-4 animate-in fade-in duration-500">
            {/* Hidden Sandbox for Rendering - Fixed A4 Ratio */}
            <div className="fixed top-0 -left-[5000px] -z-10 opacity-0 pointer-events-none">
                <div 
                    ref={previewRef} 
                    className="w-[794px] bg-white p-0 m-0 overflow-hidden" 
                    dangerouslySetInnerHTML={{ __html: htmlContent }} 
                />
            </div>

            <div className="grid lg:grid-cols-12 gap-8 items-stretch">
                {/* Editor & Upload Section */}
                <div className="lg:col-span-5 flex flex-col gap-6">
                    <Card className="flex flex-col border-2 shadow-2xl rounded-[2.5rem] overflow-hidden bg-white dark:bg-slate-950 flex-1">
                        <CardHeader className="bg-primary/5 border-b p-6 flex flex-row items-center justify-between">
                            <div className="flex items-center gap-3">
                                <div className="size-10 rounded-xl bg-primary/10 flex items-center justify-center text-primary">
                                    <FileCode className="size-5" />
                                </div>
                                <CardTitle className="text-xl font-black uppercase tracking-tighter">HTML Source</CardTitle>
                            </div>
                            <div className="flex gap-2">
                                <Button variant="ghost" size="icon" onClick={handleClear} className="h-8 w-8 text-destructive hover:bg-destructive/10" title="Clear Editor">
                                    <Trash2 className="size-4" />
                                </Button>
                            </div>
                        </CardHeader>
                        <CardContent className="flex-1 flex flex-col gap-4 p-6">
                            <div className="flex items-center justify-between">
                                <Label className="text-[10px] font-black uppercase tracking-widest text-muted-foreground flex items-center gap-2">
                                    <Globe className="size-3"/> Source Editor
                                </Label>
                                {fileName && <Badge variant="secondary" className="text-[9px] font-bold uppercase">{fileName}</Badge>}
                            </div>
                            <Textarea
                                value={htmlContent}
                                onChange={(e) => setHtmlContent(e.target.value)}
                                placeholder="Paste your HTML code here..."
                                className="flex-1 min-h-[400px] font-mono text-xs leading-relaxed border-2 focus-visible:ring-primary rounded-2xl p-6 bg-slate-900 text-slate-100 selection:bg-primary/30"
                            />
                        </CardContent>
                        <CardFooter className="p-6 bg-muted/10 border-t flex flex-col gap-4">
                            <Button 
                                variant="outline" 
                                className="w-full h-12 border-2 border-dashed border-primary/30 hover:border-primary font-black text-xs uppercase transition-all"
                                onClick={() => fileInputRef.current?.click()}
                            >
                                <UploadCloud className="mr-2 size-4" /> UPLOAD .HTML FILE
                            </Button>
                            <input 
                                ref={fileInputRef} 
                                type="file" 
                                className="hidden" 
                                accept=".html,.htm" 
                                onChange={handleFileUpload} 
                            />
                        </CardFooter>
                    </Card>
                    
                    <div className="p-5 bg-primary/5 border-2 border-primary/10 rounded-[2rem] flex gap-4 items-center">
                        <div className="size-12 rounded-full bg-primary/10 flex items-center justify-center shrink-0">
                            <ShieldCheck className="size-6 text-primary" />
                        </div>
                        <div>
                            <p className="text-[11px] font-black text-primary uppercase tracking-tight">Privacy Guard Active</p>
                            <p className="text-[10px] text-muted-foreground font-medium leading-tight">All rendering happens 100% in your browser RAM. Your source code never touches our servers.</p>
                        </div>
                    </div>
                </div>

                {/* PDF Live Result */}
                <Card className="lg:col-span-7 flex flex-col border-2 shadow-2xl rounded-[2.5rem] overflow-hidden bg-slate-100 dark:bg-slate-900">
                    <CardHeader className="bg-muted/30 border-b p-4 flex flex-row items-center justify-between">
                        <div className="flex items-center gap-2">
                            <Eye className="size-4 text-primary" />
                            <CardTitle className="text-xs font-black uppercase tracking-widest text-muted-foreground">Visual PDF Output</CardTitle>
                        </div>
                        <div className="flex items-center gap-3">
                            {isGenerating && <Loader2 className="size-3 animate-spin text-primary" />}
                            <Badge className="bg-green-600 text-white font-black text-[9px] uppercase tracking-widest px-3">Live Ready</Badge>
                        </div>
                    </CardHeader>
                    <CardContent className="flex-1 p-6 md:p-10 relative min-h-[500px] flex flex-col bg-slate-200 dark:bg-slate-800 shadow-inner overflow-y-auto max-h-[750px] custom-scrollbar">
                       {previewImage ? (
                            <div className="relative w-full shadow-2xl border-4 border-white bg-white rounded-sm mx-auto overflow-hidden animate-in zoom-in-95 duration-300">
                                <img
                                    src={previewImage}
                                    alt="Live PDF Preview"
                                    className="w-full h-auto block"
                                />
                                <div className="absolute top-0 right-0 p-2 opacity-20 pointer-events-none">
                                    <Badge variant="outline" className="text-[8px] font-black uppercase border-black">300 DPI PREVIEW</Badge>
                                </div>
                            </div>
                        ) : (
                            <div className="flex-1 flex flex-col items-center justify-center text-center p-12 gap-6">
                                <div className="relative">
                                    <Loader2 className="size-20 text-primary/10 animate-spin stroke-[4]" />
                                    <Monitor className="absolute inset-0 m-auto size-8 text-primary/20" />
                                </div>
                                <div className="space-y-2">
                                    <p className="text-sm font-black text-muted-foreground uppercase tracking-widest animate-pulse">Waiting for Code...</p>
                                    <p className="text-[10px] text-muted-foreground/60 font-medium max-w-[200px] mx-auto">Please provide HTML code or upload a file to generate high-fidelity PDF.</p>
                                </div>
                            </div>
                        )}
                    </CardContent>
                    <CardFooter className="p-8 bg-white dark:bg-slate-950 border-t flex flex-col gap-4">
                        <Button 
                            onClick={handleDownload} 
                            disabled={!pdfBlob || isGenerating} 
                            className="w-full h-18 text-xl font-black bg-primary hover:bg-primary/90 shadow-2xl rounded-2xl group active:scale-95 transition-all"
                        >
                            <Download className="mr-3 h-7 w-7 group-hover:translate-y-1 transition-transform" />
                            DOWNLOAD PROFESSIONAL PDF
                        </Button>
                        <div className="flex items-center justify-center gap-6">
                            <div className="flex items-center gap-1.5 text-[9px] font-black text-muted-foreground/50 uppercase tracking-[0.2em]">
                                <Smartphone className="size-3 text-primary" /> MOBILE OPTIMIZED
                            </div>
                            <div className="flex items-center gap-1.5 text-[9px] font-black text-muted-foreground/50 uppercase tracking-[0.2em]">
                                <Zap className="size-3 text-yellow-500" /> NATIVE SPEED
                            </div>
                        </div>
                    </CardFooter>
                </Card>
            </div>
        </div>
    );
}
