"use client";

import { useState, useRef, useEffect, useCallback, type ChangeEvent } from 'react';
import { useToast } from '@/hooks/use-toast';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from '@/components/ui/card';
import { Textarea } from '@/components/ui/textarea';
import { 
    Download, 
    Loader2, 
    FileCode, 
    Eye, 
    Globe, 
    Zap, 
    ShieldCheck, 
    Smartphone, 
    UploadCloud, 
    Trash2, 
    Monitor,
    Sparkles,
    ChevronRight,
    SearchCode,
    X,
    Settings2,
    RefreshCcw
} from 'lucide-react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { Badge } from '@/components/ui/badge';
import { Label } from '@/components/ui/label';
import { cn } from '@/lib/utils';
import { ScrollArea, ScrollBar } from '@/components/ui/scroll-area';
import { motion, AnimatePresence } from 'framer-motion';

const initialHtml = `<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #333; line-height: 1.6; background: white; }
        .hero { background: linear-gradient(135deg, #2086e1 0%, #3aa39f 100%); color: white; padding: 40px; border-radius: 24px; margin-bottom: 30px; text-align: center; }
        h1 { margin: 0; font-size: 36px; letter-spacing: -1px; }
        .card { border: 2px solid #e2e8f0; padding: 25px; border-radius: 20px; margin-top: 20px; }
        .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 20px; }
    </style>
</head>
<body>
    <div class="hero">
        <h1>Live Web Document</h1>
        <p>This is a professional HTML to PDF preview.</p>
    </div>
    <div class="card">
        <h3>Why choose local rendering?</h3>
        <p>1. <strong>100% Private:</strong> Your code never leaves your device.<br>
           2. <strong>High DPI:</strong> Text remains sharp at any zoom level.<br>
           3. <strong>Instant:</strong> See changes as you type.</p>
    </div>
    <div class="footer">Generated by GR7 Tools Hub Studio</div>
</body>
</html>`;

type Stage = 'setup' | 'editor';

export default function HtmlToPdfConverter() {
    const { toast } = useToast();
    const [stage, setStage] = useState<Stage>('setup');
    const [htmlContent, setHtmlContent] = useState<string>(initialHtml);
    const [isGenerating, setIsGenerating] = useState(false);
    const [previewImage, setPreviewImage] = useState<string | null>(null);
    const [pdfBlob, setPdfBlob] = useState<Blob | null>(null);
    const [fileName, setFileName] = useState<string | null>(null);
    const [isDragOver, setIsDragOver] = useState(false);
    
    const previewRef = useRef<HTMLDivElement>(null);
    const fileInputRef = useRef<HTMLInputElement>(null);

    const generatePdf = useCallback(async () => {
        if (!htmlContent.trim() || !previewRef.current || stage !== 'editor') {
            return;
        }

        setIsGenerating(true);
        try {
            const canvas = await html2canvas(previewRef.current, {
                scale: 2.5, // High fidelity
                useCORS: true,
                logging: false,
                backgroundColor: '#FFFFFF',
                width: 794,
            });
            
            const imgData = canvas.toDataURL('image/jpeg', 0.95);
            setPreviewImage(imgData);

            const pdf = new jsPDF({
                orientation: canvas.width > canvas.height ? 'l' : 'p',
                unit: 'px',
                format: [canvas.width, canvas.height],
            });

            pdf.addImage(imgData, 'JPEG', 0, 0, canvas.width, canvas.height, undefined, 'FAST');
            setPdfBlob(pdf.output('blob'));
        } catch (error) {
            console.error("Live preview error:", error);
        } finally {
            setIsGenerating(false);
        }
    }, [htmlContent, stage]);

    useEffect(() => {
        if (stage === 'editor') {
            const timer = setTimeout(() => {
                generatePdf();
            }, 800); 
            return () => clearTimeout(timer);
        }
    }, [htmlContent, generatePdf, stage]);

    const handleFileUpload = (e: ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (file && (file.type === 'text/html' || file.name.endsWith('.html') || file.name.endsWith('.htm'))) {
            const reader = new FileReader();
            reader.onload = (event) => {
                const content = event.target?.result as string;
                setHtmlContent(content);
                setFileName(file.name);
                setStage('editor');
                toast({ title: 'File Uploaded', description: `${file.name} loaded into editor.` });
            };
            reader.readAsText(file);
        } else if (file) {
            toast({ variant: 'destructive', title: 'Invalid File', description: 'Please upload a .html or .htm file.' });
        }
    };

    const handleDownload = () => {
        if (!pdfBlob) return;
        const url = URL.createObjectURL(pdfBlob);
        const link = document.createElement('a');
        link.href = url;
        link.download = fileName ? `${fileName.split('.')[0]}.pdf` : 'web-document.pdf';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
        toast({ title: 'Success', description: 'Your professional PDF is ready.' });
    };

    const handleClear = () => {
        setHtmlContent('');
        setFileName(null);
        if (fileInputRef.current) fileInputRef.current.value = "";
    };

    const handleReset = () => {
        setStage('setup');
        setHtmlContent(initialHtml);
        setFileName(null);
        setPreviewImage(null);
        setPdfBlob(null);
    };

    if (stage === 'setup') {
        return (
            <div className="w-full flex items-center justify-center p-4">
                <Card className={cn(
                    "w-full max-w-2xl text-center transition-all duration-300 bg-card/50 hover:border-primary/80 hover:shadow-2xl border-2 border-dashed rounded-[2.5rem] overflow-hidden",
                    isDragOver && "border-primary bg-primary/5 ring-4 ring-primary/20 scale-[1.01]"
                )}
                    onDragOver={(e) => { e.preventDefault(); setIsDragOver(true); }}
                    onDragLeave={() => setIsDragOver(false)}
                    onDrop={(e) => { e.preventDefault(); setIsDragOver(false); handleFileUpload({ target: { files: e.dataTransfer.files } } as any); }}
                >
                    <CardHeader className="pt-12 md:pt-16">
                        <div className="mx-auto mb-6 grid size-16 md:size-20 place-items-center rounded-[2rem] bg-primary/10 text-primary shadow-xl relative">
                            <FileCode className="h-8 md:h-10 w-8 md:w-10" />
                            <div className="absolute -top-1 -right-1 bg-accent text-accent-foreground size-6 rounded-full flex items-center justify-center shadow-lg animate-bounce">
                                <Sparkles className="size-3" />
                            </div>
                        </div>
                        <CardTitle className="text-2xl md:text-4xl font-black uppercase tracking-tighter">HTML to <span className="text-gradient-hero">PDF Studio</span></CardTitle>
                        <CardDescription className="text-[10px] md:text-sm uppercase font-bold opacity-60 mt-1">Transform raw code or local files into professional documents.</CardDescription>
                    </CardHeader>
                    <CardContent className="p-6 md:p-12">
                        <div
                            className="border-4 border-dashed border-muted-foreground/20 rounded-[2rem] p-10 md:p-20 flex flex-col items-center justify-center space-y-6 cursor-pointer hover:bg-muted/30 transition-all group relative"
                            onClick={() => setStage('editor')}
                        >
                            <div className="relative">
                                <UploadCloud className="h-14 md:h-20 w-14 md:w-20 text-muted-foreground group-hover:text-primary transition-colors" />
                                <Zap className="absolute -top-1 -right-1 h-6 md:h-8 w-6 md:w-8 text-yellow-500 animate-pulse" />
                            </div>
                            <div className="text-center px-4">
                                <p className="text-lg md:text-2xl font-black uppercase tracking-tighter">Click to Start Editor</p>
                                <p className="text-[10px] md:text-sm text-muted-foreground mt-2 font-bold opacity-60 uppercase tracking-widest">Or drop an .html file here.</p>
                            </div>
                        </div>
                        <input ref={fileInputRef} type="file" className="hidden" accept=".html,.htm" onChange={handleFileUpload} />
                    </CardContent>
                    <CardFooter className="justify-center gap-6 md:gap-10 text-[8px] md:text-[10px] text-muted-foreground font-black uppercase tracking-widest pb-10 bg-muted/10 pt-6 px-4">
                        <div className="flex items-center gap-1.5"><ShieldCheck className="size-3 text-green-600" /> SECURE RAM</div>
                        <div className="flex items-center gap-1.5"><SearchCode className="size-3 text-primary" /> LIVE RENDER</div>
                        <div className="flex items-center gap-1.5"><Sparkles className="size-3 text-purple-500" /> 300 DPI HD</div>
                    </CardFooter>
                </Card>
            </div>
        );
    }
    
    return (
        <div className="w-full flex flex-col gap-6 animate-in fade-in duration-700 px-4 max-w-[1800px] mx-auto pb-20">
            {/* Hidden Sandbox for Rendering */}
            <div className="fixed top-0 -left-[5000px] -z-10 opacity-0 pointer-events-none">
                <div 
                    ref={previewRef} 
                    className="w-[794px] bg-white p-0 m-0 overflow-hidden" 
                    style={{ minHeight: '1123px' }}
                    dangerouslySetInnerHTML={{ __html: htmlContent }} 
                />
            </div>

            <div className="flex flex-col md:flex-row items-center justify-between gap-4 md:gap-6">
                <div className="flex items-center gap-3">
                    <div className="size-10 md:size-12 rounded-xl bg-primary/10 flex items-center justify-center text-primary shadow-lg border border-primary/20 shrink-0">
                        <Settings2 className="size-5 md:size-6" />
                    </div>
                    <div>
                        <h2 className="text-lg md:text-2xl font-black uppercase tracking-tighter">Studio <span className="text-primary">Panel</span></h2>
                    </div>
                </div>
                <div className="flex gap-2 w-full md:w-auto">
                     <Button variant="outline" onClick={handleReset} className="flex-1 md:flex-none h-9 md:h-10 border-2 font-black text-[8px] md:text-[9px] uppercase px-4 rounded-lg">
                        <RefreshCcw className="mr-1.5 size-3" /> Reset
                    </Button>
                    {pdfBlob && (
                        <Button size="lg" className="flex-[2] md:flex-none h-9 md:h-10 px-8 bg-green-600 hover:bg-green-700 font-black text-[9px] md:text-xs rounded-lg shadow-xl" onClick={handleDownload}>
                            <Download className="mr-1.5 size-3.5" /> DOWNLOAD PDF
                        </Button>
                    )}
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start w-full">
                {/* Editor Section (Left Sidebar style but wider for code) */}
                <div className="lg:col-span-5 flex flex-col gap-6">
                    <Card className="flex flex-col border-2 shadow-2xl rounded-[2rem] overflow-hidden bg-white dark:bg-slate-950 flex-1 border-primary/10">
                        <CardHeader className="bg-primary/5 border-b p-4 md:p-6 flex flex-row items-center justify-between">
                            <div className="flex items-center gap-3">
                                <div className="size-10 rounded-xl bg-primary/20 flex items-center justify-center text-primary shadow-inner">
                                    <FileCode className="size-5" />
                                </div>
                                <CardTitle className="text-sm md:text-base font-black uppercase tracking-tighter">HTML Source Editor</CardTitle>
                            </div>
                            <div className="flex gap-1.5">
                                <Button variant="ghost" size="icon" onClick={handleClear} className="h-8 w-8 text-destructive hover:bg-destructive/10 rounded-lg">
                                    <Trash2 className="size-4" />
                                </Button>
                            </div>
                        </CardHeader>
                        <CardContent className="flex-1 flex flex-col gap-4 p-6 md:p-8">
                            <div className="flex items-center justify-between px-1">
                                <Label className="text-[9px] font-black uppercase tracking-widest text-muted-foreground flex items-center gap-2">
                                    <Globe className="size-3 text-primary"/> Main Sandbox
                                </Label>
                                {fileName && <Badge variant="secondary" className="text-[8px] font-black uppercase truncate max-w-[150px]">{fileName}</Badge>}
                            </div>
                            <Textarea
                                value={htmlContent}
                                onChange={(e) => setHtmlContent(e.target.value)}
                                placeholder="Paste your HTML code here..."
                                className="min-h-[500px] md:min-h-[650px] font-mono text-[10px] md:text-xs leading-relaxed border-2 focus-visible:ring-primary rounded-2xl p-6 bg-slate-900 text-slate-100 custom-scrollbar shadow-inner"
                            />
                        </CardContent>
                        <CardFooter className="p-4 md:p-6 bg-muted/20 border-t flex flex-col gap-3">
                            <Button 
                                variant="outline" 
                                className="w-full h-12 border-2 border-dashed border-primary/30 hover:border-primary font-black text-[10px] uppercase rounded-xl transition-all"
                                onClick={() => fileInputRef.current?.click()}
                            >
                                <UploadCloud className="mr-2 size-4" /> Load Local .html File
                            </Button>
                            <input ref={fileInputRef} type="file" className="hidden" accept=".html,.htm" onChange={handleFileUpload} />
                        </CardFooter>
                    </Card>
                    
                    <div className="p-5 md:p-6 bg-green-500/5 border-2 border-green-500/10 rounded-[2rem] flex gap-4 items-center shadow-sm">
                        <div className="size-10 md:size-12 rounded-full bg-green-500/10 flex items-center justify-center shrink-0 shadow-inner">
                            <ShieldCheck className="size-5 md:size-6 text-green-600" />
                        </div>
                        <div>
                            <p className="text-[10px] md:text-[11px] font-black text-green-700 uppercase tracking-tight">Industrial Safe Guard</p>
                            <p className="text-[8px] md:text-[9px] text-muted-foreground font-bold leading-tight uppercase mt-0.5">Your code and data stays 100% in local RAM. Zero cloud leaks.</p>
                        </div>
                    </div>
                </div>

                {/* PDF Live Result (Main Viewport) */}
                <Card className="lg:col-span-7 flex flex-col border-2 shadow-3xl rounded-[2.5rem] overflow-hidden bg-slate-100 dark:bg-slate-900 border-primary/10 min-h-[600px] md:h-full">
                    <CardHeader className="bg-muted/30 border-b p-4 md:p-6 flex flex-row items-center justify-between">
                        <div className="flex items-center gap-2">
                            <Eye className="size-4 text-primary" />
                            <CardTitle className="text-[10px] font-black uppercase tracking-[0.2em] text-muted-foreground">HD STUDIO RENDER</CardTitle>
                        </div>
                        <div className="flex items-center gap-3">
                            {isGenerating && <Loader2 className="size-4 animate-spin text-primary opacity-50" />}
                            <Badge className="bg-primary text-white font-black text-[9px] uppercase tracking-widest px-3 py-1 rounded-full border-2 border-white shadow-md">A4 CANVAS</Badge>
                        </div>
                    </CardHeader>
                    <CardContent className="flex-1 p-4 md:p-12 relative min-h-[500px] md:min-h-[700px] flex flex-col bg-slate-200 dark:bg-slate-800 shadow-inner overflow-hidden">
                        <ScrollArea className="flex-1 w-full h-full">
                            <div className="flex justify-center p-2 md:p-4">
                                <AnimatePresence mode="wait">
                                    {previewImage ? (
                                        <motion.div 
                                            initial={{ scale: 0.95, opacity: 0 }} 
                                            animate={{ scale: 1, opacity: 1 }}
                                            className="relative w-full max-w-[550px] shadow-[0_45px_100px_-20px_rgba(0,0,0,0.5)] border-[8px] border-white bg-white rounded-sm overflow-hidden"
                                        >
                                            <img src={previewImage} alt="Live PDF Preview" className="w-full h-auto block" />
                                            <div className="absolute top-2 right-2 p-1.5 opacity-20 pointer-events-none">
                                                <Badge variant="outline" className="text-[7px] font-black uppercase border-black">HD DPI</Badge>
                                            </div>
                                        </motion.div>
                                    ) : (
                                        <div className="flex-1 flex flex-col items-center justify-center text-center p-20 gap-6 opacity-20">
                                            <div className="relative">
                                                <Loader2 className="size-20 md:size-24 text-primary animate-spin stroke-[3]" />
                                                <Monitor className="absolute inset-0 m-auto size-8 md:size-10 text-primary animate-pulse" />
                                            </div>
                                            <p className="text-sm md:text-base font-black text-muted-foreground uppercase tracking-[0.3em] animate-pulse">Rendering Code View...</p>
                                        </div>
                                    )}
                                </AnimatePresence>
                            </div>
                            <ScrollBar />
                        </ScrollArea>
                        
                        <div className="absolute bottom-6 left-1/2 -translate-x-1/2 flex items-center gap-3 px-8 py-2.5 bg-black/80 backdrop-blur-xl rounded-full text-white text-[10px] font-black uppercase tracking-widest border border-white/10 shadow-3xl z-40">
                             <SearchCode className="size-4 text-primary animate-pulse" /> Real-time Mapping Active
                        </div>
                    </CardContent>
                    <CardFooter className="p-6 md:p-10 bg-white dark:bg-slate-950 border-t flex flex-col sm:flex-row gap-4 items-center">
                        <Button 
                            onClick={handleDownload} 
                            disabled={!pdfBlob || isGenerating} 
                            className="w-full h-16 md:h-20 text-lg md:text-2xl font-black bg-primary hover:bg-primary/90 shadow-2xl rounded-2xl md:rounded-[1.5rem] group active:scale-95 transition-all flex items-center justify-center"
                        >
                            <Download className="mr-3 h-6 w-6 md:h-9 md:w-9 group-hover:translate-y-1 transition-transform" />
                            DOWNLOAD PROFESSIONAL PDF
                        </Button>
                        <div className="flex flex-col items-center justify-center gap-1 text-muted-foreground/30 text-[8px] font-black uppercase tracking-widest shrink-0">
                            <div className="flex items-center gap-1.5"><Smartphone className="size-3 text-primary" /> MOBILE SYNC</div>
                            <div className="flex items-center gap-1.5"><Zap className="size-3 text-yellow-500" /> NATIVE ENGINE</div>
                        </div>
                    </CardFooter>
                </Card>
            </div>
        </div>
    );
}
